# Bacteremia
 
Bacteremia: Interpreting Verigene® Results – VASP

Background

-   -   -   -   -   

-   When BCx turn positive, the lab reports Gm stain and Verigene®
    results to help guide empiric therapy, while awaiting further
    species identification and susceptibilities.

Management

-   Start empiric antibiotic therapy (based on clinical picture and
    table below)
-   Consider ordering repeat BCx x2 based on organism to document
    clearance
    -   Repeat for: Staph (MRSA or MSSA), Strep lugdunensis
-   If source control & no endovascular infxn, **no need to repeat**
    (most other strep and GNR’s
-   VUMC antibiograms
    can be used to reference typical resistance patterns and most common
    organisms in blood cultures.
-   Consider clinical picture: Do you have a likely source of
    bacteremia? Do you need to consider/assess for additional sources of
    infection?
-   Candida in
    a blood culture is **NEVER** considered a contaminant
-   Do not hesitate to consult Infectious Diseases (or page
    **615-317-GERM** ) with questions <span id="section-2"></span>
-   Species identification and susceptibility is available in 2-3 days
    from positive culture

**GRAM POSITIVE COCCI**

| 0                                                                                                  | 1                     | 2                                                                                 |
|----------------------------------------------------------------------------------------------------|-----------------------|-----------------------------------------------------------------------------------|
| Organism                                                                                           | Resistance Marker     | Preliminary Recommendation                                                        |
| Staphylococcus aureus or Staphylococcus lugdunensis                                                | mecA detected         | Start vancomycin IV                                                               |
| Staphylococcus aureus or Staphylococcus lugdunensis                                                | No mecA detected      | Start nafcillin or cefazolin Stop empiric vancomycin IV                           |
| Staphylococcus epidermidis - Often skin contaminant - Repeat cultures, start  therapy if uncertain | mecA detected         | Start vancomycin IV                                                               |
| Staphylococcus epidermidis - Often skin contaminant - Repeat cultures, start  therapy if uncertain | No mecA detected      | Start nafcillin or cefazolin Stop empiric vancomycin IV                           |
| Other coagulase negative Staph Often skin contaminant Repeat cultures start abx if uncertain       | NaN                   | Start vancomycin IV                                                               |
| Streptococcus: agalactiae, pyogenes, anginosus                                                     | NaN                   | Start penicillin IV Stop empiric vancomycin                                       |
| Streptococcus pneumoniae                                                                           | NaN                   | Start ceftriaxone Stop empiric vancomycin Await PCN sensitivity data              |
| Other Streptococcus                                                                                | NaN                   | Continue empiric vancomycin, awaiting susceptibilities                            |
| Enterococcus faecalis                                                                              | vanA or vanB detected | Start daptomycin 8-10mg/kg/day IV Don’t treat w vancomycin IV Contact precautions |
| Enterococcus faecalis                                                                              | No vanA or vanB       | Start ampicillin Stop empiric vancomycin IV                                       |
| Enterococcus faecium                                                                               | vanA or vanB detected | Start daptomycin 8-10mg/kg/day IV Don’t treat w vancomycin IV Contact precautions |
| Enterococcus faecium                                                                               | No vanA or vanB       | Start vancomycin IV                                                               |

GRAM POSITIVE RODS

| 0                                                                                          | 1                                           |
|--------------------------------------------------------------------------------------------|---------------------------------------------|
| Organism                                                                                   | Preliminary Recommendation                  |
| Listeria monocytogenes                                                                     | Start ampicillin Stop empiric vancomycin IV |
| Other Gram positive rod Often skin contaminant Repeat cultures, start therapy if uncertain | Start vancomycin IV                         |

GRAM NEGATIVE RODS \*Consult ID if carbapenem resistance detected\*

| Organism                         | Resistance Marker     | Preliminary Recommendation                                        |
|----------------------------------|-----------------------|-------------------------------------------------------------------|
| Acinetobacter species            | None                  | Start IV meropenem 1g q8h IV until sensitivities available        |
| Acinetobacter species            | ESBL (CTX-M)          | Start meropenem 1g q8h IV Consider ID consult Contact precautions |
| Acinetobacter species            | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
| Citrobacter or Serratia species  | None                  | Start cefepime 2g q8h IV                                          |
| Citrobacter or Serratia species  | ESBL (CTX-M)          | Start carbapenem therapy contact precautions                      |
| Citrobacter or Serratia species  | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
| Enterobacter species             | None                  | Start cefepime 2g q8h IV                                          |
| Enterobacter species             | ESBL (CTX-M)          | Start carbapenem therapy contact precautions                      |
| Enterobacter species             | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
| Escherichia coli                 | None                  | Start IV ceftriaxone 2g q24h IV                                   |
| Escherichia coli                 | ESBL (CTX-M)          | Start carbapenem therapy Contact precautions                      |
| Escherichia coli                 | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
| Klebsiella pneumoniae or oxytoca | None                  | Start ceftriaxone 2g q24h IV                                      |
| Klebsiella pneumoniae or oxytoca | ESBL (CTX-M)          | Start carbapenem therapy Contact precautions                      |
| Klebsiella pneumoniae or oxytoca | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
| Proteus species                  | None                  | Start ceftriaxone 2g q24h IV                                      |
| Proteus species                  | ESBL (CTX-M)          | Start carbapenem therapy Contact precautions                      |
| Proteus species                  | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
| Pseudomonas aeruginosa           | None                  | Start IV cefepime 2g q8h IV                                       |
| Pseudomonas aeruginosa           | ESBL (CTX-M)          | Start meropenem (do not start ertapenem) Contact precautions      |
| Pseudomonas aeruginosa           | carbapenem resistance | Consult Infectious Diseases Contact precautions                   |
