# GU infection
 
Genitourinary Infection – VASP

Asymptomatic Bacteriuria

Background

-   Isolation
    of bacteria in an appropriately collected urine specimen from an
    individual without symptoms or signs of urinary tract infection.
    Bacteriuria, foul odor, urine appearance, pyuria and/or bacteriuria
    alone are not indicative of infection.
-   Anuric ESRD patients may have bacteriuria from colonization due to
    lack of flushing of bladder, avoid sending UA/Ucx unless patient is
    symptomatic
-   Treatment
    only required for specific populations:
    -   Pregnant women (screening performed at 12 – 16 weeks)
    -   Anticipated urologic intervention
    -   Some
        renal transplant recipients, depending on time since transplant

Uncomplicated Urinary Tract Infection (UTI)

Background

-   Clinical
    symptoms of UTI (dysuria/urgency/frequency/ hematuria) in
    non-pregnant, immunocompetent, neurologically-intact pts with normal
    urologic anatomy and no indwelling urinary catheters
-   Treatment \< 5 days is not adequate when treating with a
    beta-lactam. Avoid amoxicillin or ampicillin due to increasing
    resistance
-   Nitrofurantoin cannot be used for ascending UTI or pyelonephritis
-   Antibiotics should be tailored if culture data are available.

Evaluation

-   Assessment
    of urinary symptoms
-   UA
    \+ reflex urine Cx (Cx if pt is admitted or has recurrent UTIs)
-   Non
    -reflex urine Cx: pregnant pts, neutropenia, and pts undergoing
    urologic procedures

Management

-   Empiric
    therapy
    -   Nitrofurantoin monohydrate: 100 mg PO BID x 5 days (avoid if any
        concern for pyelonephritis or if creatinine clearance \<60)
    -   Cephalexin
        250-500mg q6h x5-7 days
-   Alternative
    therapies
    -   Fosfomycin: 3 grams of powder mixed in water as a single PO dose
        (avoid if any concern for ascending UTI or pyelonephritis).
        Susceptibility test results must be requested of micro lab and
        are only possible for E. coli and E. Faecalis.
    -   Amoxicillin
        -clavulanate: 500mg PO BID x5 days
    -   Ciprofloxacin
        : 250mg PO BID x3 days
        -   FQ’s should be reserved for more serious infections than
            uncomplicated cystitis, and only after susceptibility
            results are confirmed given high rates of resistance from
            overuse (\~25% of *E. coli* are resistant to ciprofloxacin
            at VUMC)
        -   Adverse effect profile >\> beta-lactams (i.e.
            QT-prolongation, tendinopathies)

Additional

Information

-   MDR cystitis: ESBL
    isolates are increasingly common due to antibiotic overuse
-   Before treating, decide if this is a TRUE UTI
-   If true, then for uncomplicated cystitis with ESBL organism,
    consider Fosfomycin (if *E. coli* ) or nitrofurantoin (if
    susceptibility is confirmed – *K. pneumoniae* and *Enterobacter* spp
    are usually resistant), or ID consultation
-   Ask the lab to check susceptibility results to these antibiotics,
    for the future reference

Complicated UTI and Pyelonephritis

Background

-   Fever
    , pyuria, and costovertebral angle tenderness suggest
    pyelonephritis. If any of the following are present, it is also
    considered a complicated UTI
-   UTI
    with any of the following present:
    -   Renal calculi or other obstructive disease, Immunosuppressed
        host, abnormal urological anatomy or physiology, presence of a
        urinary catheter

Evaluation

-   -   -   -   -   

-   UA with reflex urine culture

-   BCx and UCx prior to antibiotics

-   If there is no pyuria, consider an alternative diagnosis, or
    proximal ureteral obstruction
    -   Pyuria
        is common in the presence of a urinary catheter, kidney stones,
        urostomy, ileal conduit and other invasive devices, and may not
        indicate infection

Management

-   Duration: 7-14 days, depending on antibiotic choice
-   Follow up culture to confirm clearance, especially if outpatient
-   Tailor therapy once/if cultures are available. If no improvement in
    48h, consider imaging to rule out complications (e.g., perinephric
    abscess)

| 0          | 1                                                                                             | 2                                                                                                                                                                 |
|------------|-----------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| NaN        | First Line                                                                                    | Alternative                                                                                                                                                       |
| Outpatient | Ciprofloxacin 750 BID (or 500 BID if bacteremia r/o)  x 7d                                    | NaN                                                                                                                                                               |
| Inpatient  | \- CTX 2g q24h - Cefepime 2g q8h - Meropenem 2g q8h (if h/o or confirmed ESBL w/in last 90 d) | \- Ertapenem 1g q24 instead of Meropenem if no Pseudomonas - Ciprofloxacin 750 PO BID (500 PO BID if bacteremia ruled out) OR 400 IV BID (if suscept confirmed)\* |

\*FQ’s have same bioavailability if given PO or IV so oral is preferred

Catheter Associated Urinary Tract Infection (CAUTI)

Background

-   Culture growth of > 10 <sup>3</sup> cfu/mL of uropathogenic
    bacteria + signs or symptoms consistent with infection (without
    another identified etiology) + indwelling urethral/suprapubic
    catheter or intermittent catheterization.
    -   This includes pts with catheters in place during the preceding
        48 hours
-   Duration = greatest risk factor (Increases 3-10% per day of
    catheterization)
    -   Other risks: female sex, diabetes, elderly, colonization of
        catheter bag, poor care
-   Bacteriuria, foul odor, pyuria, urine appearance and/or bacteriuria
    alone are not indicative of infection in patients who are otherwise
    asymptomatic.
-   Ensure clean sample collected
    -   Ideally, catheter is removed and midstream sample obtained
    -   If catheterization required; removal of old catheter and sample
        taken from new

Management

-   -   -   -   -   

-   Distinguish uncomplicated vs complicated UTI (see above)

-   Antimicrobial management:
    -   Guided by cultures and susceptibilities
    -   Empiric guidance as per management of uncomplicated/complicated
        UTI and per prior culture data/susceptibilities when available
    -   Duration: 7 – 14 days depending on antibiotic, clinical response
        and whether infection constitutes complicated vs uncomplicated
        UTI
    -   Special note regarding **Candida** UTI management: Candida Is
        generally not pathogenic
    -   Presence
        in urine does not indicate infection (unless perinephric
        abscess, renal transplant, or complex fistulous disease)
    -   Fluconazole
        achieves excellent urinary penetration
    -   Echinocandins do not, and other azoles are not well studied in
        UTIs
    -   If
        fluconazole
        resistant Candida cultured or suspected, consult ID
    -   Susceptibilities are not routinely run on Candida from urine
        cultures and would need to be requested if concern for true
        infection.

-   Catheter management
    -   At the least, catheters should be replaced at the time of
        antibiotic initiation
    -   Preferably, catheters should be removed
    -   If catheterization is necessary, intermittent catheterization is
        preferred over continuous use. Condom catheters and pure wicks
        preferred over foley catheter
