# Knee Pain
 
Knee Pain – Samuel Lazaroff

Background

-   Key features of the history include location: have patient point to
    the area that hurts most
-   Septic arthritis can also present indolently, with well-appearing,
    afebrile, patients
-   History of trauma, swelling, systemic symptoms, weight-bearing
-   Consider mechanism of injury
    à
    presence/absence of effusion
    à
    location
    -   High-energy trauma:  high risk of bony and/or ligamentous injury
    -   Low-Energy Trauma and Atraumatic etiologies organized by
        location

| 0             | 1                                                                                                                     | 2                                                                                                            |
|---------------|-----------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| Knee Location | Low-Energy Trauma                                                                                                     | Atraumatic                                                                                                   |
| Anterior      | Patellar subluxation or dislocation (instability) Patellar fracture Patellar tendon rupture Quadriceps tendon rupture | Tendinopathy: patellar or quadricep Hoffa’s fat pad syndrome (inflammation of post-patellar fat) Bursitis OA |
| Medial        | MCL tear Acute medial meniscus tear                                                                                   | Medial meniscus degenerative tear Pes anserine bursitis OA                                                   |
| Lateral       | LCL tear Acute lateral meniscus tear                                                                                  | IT band syndrome Lateral meniscus degenerative tear OA                                                       |
| Posterior     | PCL tear Hyperextension                                                                                               | Baker’s cyst Popliteal art. aneurysm/entrapment                                                              |
| Generalized   | ACL tear PCL tear Intra-articular fracture                                                                            | Patellofemoral pain syndrome OA Patellar stress fracture Referred from hip or ankle                          |

Presentation

-   Traumatic Effusion:
    -   Differential is ACL or PCL rupture, meniscus tear, patellar
        instability (dislocation of subluxation), bone bruise, fracture
-   Atraumatic Effusion:
    -   Activity related or pain w/activity: Osteoarthritis,
        Osteochondral injury
-   Not activity-related: Consider autoimmune causes, crystalline
    arthropathy, Lyme disease, Septic arthropathy (including gonococcal)
-   Less common causes: primary bone tumor, viral infection
    (Parvo), hyperparathyroidism, hemochromatosis, syphilis, sarcoid,
    Whipple’s

Evaluation

-   Physical Exam:
    -   Inspection, palpation, AROM, PROM, strength, check for effusion,
        neurovascular exam (incl. reflexes if applicable), provocation
        (of ligaments), gait
    -   Examine the back, hip, and ankle as well
-   Aspirate if effusion present
-   Ottawa Knee Rule = Imaging if 1 of following:
    -   \>
        55 y/o
    -   Isolated tenderness of patella
    -   Tenderness of fibular head
    -   Unable to flex 90° º
    -   Unable to ambulate 4 steps at time of injury and at time
        of evaluation

| 0                             | 1                             | 2                                                                                                                                            | 3                                           |
|-------------------------------|-------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------|
| Provocation Tests of the Knee | Provocation Tests of the Knee | Provocation Tests of the Knee                                                                                                                | Provocation Tests of the Knee               |
| Test                          | Isolates                      | Action                                                                                                                                       | Positive if                                 |
| Anterior Drawer               | ACL                           | Hip flexed and knee in 90° of flexion, pull anteriorly on tibia                                                                              | Tibia translates forward                    |
| Pivot Shift                   | ACL                           | With knee extended, internally rotate the foot and apply valgus force                                                                        | Translation of femur or tibia               |
| Lachman                       | ACL                           | With knee flexed 20°, hold thigh down with one hand while pulling anteriorly on tibia with your other hand (with thumb on tibial joint line) | Soft end point of tibial translation        |
| Posterior drawer              | PCL                           | With hip flexed and knee in 90° of flexion, push posteriorly on tibia                                                                        | Tibia translates backwards                  |
| Joint line tenderness         | Meniscus                      | Palpate                                                                                                                                      | Reproduces pain at site                     |
| McMurray                      | Meniscus                      | With hip & knee flexed, apply: Medial: valgus force and internal rotate foot Lateral: varus force and externally rotate foot                 | Click, pop, or reproduces pain              |
| Noble Compression             | IT band                       | Patient lies on unaffected side, flex knee while pressure applied to distal IT band (lateral epicondyle)                                     | Click, pop, or reproduces pain              |
| Patellar compression          | Patello-femoral pain          | With knee extended and quads relaxed, apply direct pressure to anterior patella as patient tightens quads                                    | Reproduces pain                             |
| Patellar apprehension         | Patello-femoral pain          | With knee flexed to 30°, displace patella laterally                                                                                          | Patient grimaces or tries to straighten leg |

Imaging

-   X-ray: b/l AP, unilateral, lateral, b/l sunrise view
-   Obtain X-rays in standing position (or joint space narrowing may not
    be apparent)
-   MSK U/S: allows for dynamic imaging and is ≈100% sensitive
    for effusion
-   Also visualizes ligaments, muscles/tendons, joint space,
    and vasculature
-   MRI:  indicated after failure of conservative management or when
    considering surgical repair

Treatment:

-   RICE (rest, ice, compression, elevation) for acute injuries
-   Bracing
-   NSAIDs: see prior section for anti-inflammatory dosing
-   Physical therapy for 4-6 weeks for ligamentous, muscular, or
    meniscal injury
-   Antibiotics may be appropriate for bursitis if infection
    is suspected
-   Referral to orthopedics/sports medicine if no improvement after
    conservative therapy
    -   Surgery reserved for young, athletic people with
        ligamentous injury
