# DHT
 
Video Guide:

https://www.youtube.com/watch?v=qUh5AJ5uIZo

Indications

-   Enteral feeding if unable to swallow; passing meds
-   DHT deliver meds and fluids, NGT provide suction to decompress (can
    also deliver meds/fluids); nurses place NGT, residents (and ICU
    nurses) place DHT

Relative Contraindications

-   Esophageal varices or strictures (most hepatologists say this is not
    a contra-indication)
-   Other altered gastric anatomy that may prevent passage. (i.e.
    gastric bypass, esophageal hernias, tumors or other possible
    obstructions).

Absolute Contraindications for blind approach

-   Facial (increased risk of intracranial placement), pharyngeal or
    esophageal trauma

Procedure considerations

-   Silicone-based, flexible tubing, less than 12fr in size, can be left
    in place for longer periods of time. NGTs are PVC-based, more rigid,
    and larger allowing gastric decompression
-   Prior to placement, fully fasten the stylet in the fully-hubbed
    position to reduce bending and folding over of the weighted tip
    while advancing
-   Make sure DHT and bridle sizes correlate

Group consensus and recommendations

-   Anesthetic use with lidocaine gel (order Lidocaine uro-jet) and
    nasal swab; reduces pt discomfort, reduces gag reflex, and assists
    with clearance of the nasal passages
-   Have the patient sit upright with the head tilted toward the chest
    to encourage posterior oropharynx positioning of the DHT while
    advancing.
-   If pt can participate safely, have the patient swallow before
    advancement; pt can suck on straw to utilize pharyngeal muscles to
    position DHT into esophagus
-   Excessive coughing, difficulty phonating, or resistance may indicate
    trachea placement. Withdraw tube and re-attempt. Consider Duoneb to
    reduce bronchospasms
-   3 failed attempts should be made at the bedside before sending for
    fluoro-guidance
-   When post-pyloric placement is requested, 1 attempt at post-pyloric
    placement with the blind approach at the bedside is acceptable
    before referring to fluoroscopic guidance

Placement Tips & Tricks

-   Insufflation of air and auscultation of bowel sounds over the
    gastric area can be reassuring of correct placement of DHT prior to
    bridling and leaving the bedside.  Always obtain KUB for
    radiological confirmation of placement. Leaving the stylet in for
    confirmation can make it easier to see on KUB and can allows
    re-advancement
-   Place bridle and dog-bone tape while at the bedside to reduce
    dislodgement
-   When placing bridle, keep alignment markers (as clearly marked on
    both probes) together so magnetic tips will align once past the
    nasal septum
-   When placing the bridle, remove the green stylet housed within the
    white probe before retracting back and removing the white probe

Post-pyloric placement

-   Consider in patients with high pulmonary aspiration risk and severe
    esophageal reflux/esophagitis, recurrent emesis, impaired gastric
    motility, and pancreatitis
-   Post-pyloric placement has been shown up to 90% successful with
    intermittent insufflation of 10-20cc of air \~every 10cm of
    advancement after 55cm to promote pylorus opening. IV Reglan or
    Erythromycin may also help

Post-procedural considerations

-   ALWAYS confirm the position radiographically before medications are
    given!
-   Most mispositioned/coiled tubes have to be removed and re-attempted,
    but it is ok to advance or withdraw if Stylet is still in place.
    However, once removed, a stylet should not be re-introduced to a
    mispositioned/coiled tube due to risk of GI perforation
-   Listen to the patient, repeat imaging (Plain film or CT) if concern
    for any perforation, and notify appropriate surgical service.
-   In case of cranial placement, don’t remove, consult NSGY
-   De-clogging: Clog Zapper Kit (can type this into Epic directly);
    Coca cola
