# Paracentesis
 
Video Guide:

https://www.youtube.com/watch?v=pQSsb9705LE&t=160s

Indications

-   Diagnostic: Evaluation of new onset ascites, or known ascites in pts
    with clinical decompensation, fever, abdominal pain/tenderness, HE,
    leukocytosis, AKI
-   Therapeutic: large volume ascites resistant to diuretics causing pt
    discomfort

Pre-Procedural considerations

-   If therapeutic, determine volume pt typically gets drained so you
    have enough bottles
-   Labs (order before so nurse can print off labels): cell count
    w/diff, BF culture, BF & serum albumin, total protein; cytology if
    c/f malignancy; BF/serum Hct if bloody

Procedural considerations

-   Ultrasound Probe: curvilinear, to identify safe pocket (\~2 cm)
-   Kit: 6 Fr Safe-T-Centesis Kit
-   If only diagnostic, use 18G needle with 20-50cc syringe rather than
    kit
-   If high bleeding risk, use long 18 g. needle & attach to syringe
    instead of 6 Fr. Catheter
-   Avoid surgical scars out of concern for nearby adhesions and
    superficial veins
-   Z-track
    method: may reduce post-paracentesis ascitic fluid leakage. Once
    into subcutaneous tissue, move superior/inferior to allow tissue
    overlap.
-   Attempt as lateral as possible to avoid inferior epigastric vessels
-   Roll patient to left or right side to promote pooling of fluid for
    easier/safer access
-   Inoculate culture bottles at bedside rather than sending fluid
    samples to lab for inoculation to increase yield 50%
    
    80% (VA does not allow bedside inoculation.)
-   If hernia present, have patient reduce it while draining fluid to
    prevent incarceration

Post-procedural considerations

-   Albumin for large volume (>5L): give 8 grams per liter removed
-   Ascitic leak: roll pt on opposite side; place 1 figure-of-eight
    stitch with 4.0 vicryl
-   Bleeding complication – Hold pressure with quick-clot and gauze
    for >5-10 if persistent bleeding at site; if profuse bleeding or
    concern for organ injury, STAT page EGS
