# Inpatient Headache
 
| 0                       |
|-------------------------|
| Inpatient Headache (HA) |

Background

-   Important to distinguish 1º° and 2º° headache
-   Red flags for
    2º° **headaches (SNOOP):** **S** ystemic symptoms, **N** eurologic
    symptoms, **O** nset that is sudden (thunderclap), **O** lder age
    (new headache >40), **P** rogression or evolution in previous
    headaches \[the ‘P’ is also used for **P** ositional component\]
    -   Other red flags: preceding trauma, HA awakening pt from sleep,
        no HA-free intervals
    -   Thunderclap suggests that maximal HA intensity develops within
        10 seconds

Evaluation

-   Get a good description of where the pain is, when, associated
    symptoms, and assess for “red flag” features listed above
-   If there are any red flag features imaging and workup are necessary
-   Imaging depends on highest suspicions, but CTA head/neck is
    appropriate to evaluate for aneurysm (including neck to consider
    dissection). If any focal signs, MRI is generally preferred; venous
    imaging can be beneficial in headaches with features of elevated ICP
-   If no red flag features, then workup is not necessary, and focus is
    on treatment

Management

-   NSAIDs and Tylenol for infrequent headaches, but consistent use
    (>2-3 a week) runs the risk of rebound headaches
-   Triptans for migraine, but contraindicated in patients with CAD,
    uncontrolled HTN, previous stroke
    -   There are theoretical concerns of serotonin syndrome when used
        with SSRI/SNRIs
-   Acute migraine in hospital: “migraine cocktail” -> 1 L fluid bolus,
    2-4 grams of magnesium sulfate, IV Compazine
    (10mg)/Phenergan(20mg)/Reglan (20mg) with Benadryl (25mg)
    -   If that does not work: Depakote 1000 mg IV, decadron 10mg IV ,
        +/- toradol 30mg IV, flexeril 10mg PO
-   Cluster headache – also responds to triptans, high flow O2 (>10 L),
    sometimes intranasal lidocaine if no arrhythmia history
