# Elevated ICP and Hydrocephalus
 
Elevated Intracranial Pressure and Hydrocephalus

Background

-   Communicating hydrocephalus: can be 2/2 subarachnoid granule
    scarring after subarachnoid hemorrhage or meningitis, ependymoma
    producing excess CSF, venous sinus thrombosis
-   Non
    -communicating hydrocephalus (i.e. obstructive) - usually due to a
    mass lesion such as a tumor, abscess, or hematoma in the midline
    ventricular structures
-   Eventually, elevated intracranial pressures will cause herniation of
    brain

Presentation

-   Headache
    , blurred vision, visual field reduction, enlarged blind spot, may
    pass out, develop nausea or vomiting followed by coma
-   Sixth nerve palsies are common with elevated ICP
-   Compressive 3 <sup>rd</sup> nerve palsies are classically associated
    with uncal herniation

Evaluation

-   Need a good visual exam: look for restricted visual fields, enlarged
    blind spot, papilledema (may not be present if very rapid ICP
    increase, even with vision loss), and 6 <sup>th</sup> nerve palsies
-   Stat head CT to look for obstructions, mass lesions
-   Venous imaging is also usually necessary: CTV or MRV to look for
    venous sinus thrombosis
    -   Venous sinus thrombosis needs AC, even if there is some degree
        of hemorrhagic infarction
-   Obstructive lesions require NSGY eval for either removal of the
    lesion or a ventricular drain
-   If
    no
    obstructive lesion, then LP will be needed for opening pressure
-   If workup is normal, except for elevated opening pressure, it is IIH

Management

-   Idiopathic intracranial hypertension (IIH) is treated with diamox
    and/or topiramate
    -   Patients with IIH will need ophthalmology evaluation emergently,
        if there is severe disc edema then nerve sheath fenestrations or
        urgent VPS placement may be needed.
    -   If there is clinical concern for herniation:
        -   Mannitol – 50 grams IV, can be given peripherally. Has risks
            of renal injury
        -   Hypertonic saline – 3%, 7% or 23% saline can be given, needs
            central access
        -   Maintain
            head of bed at least 30° and loosen neck obstructions
            (c-collars) as able
        -   NSGY consult for shunt consideration
    -   Hyperventilation is controversial but can be done with goal
        PaCO2 30-34 mm Hg or ETCO2 20-30 mmHg
        -   If lower, there is concern for cerebral ischemia
        -   After 4-6 hrs, compensatory pH changes in the blood prevent
            vasoconstrictive affects
