# ACS
 
Acute Coronary Syndrome - Nick King

Background

-   Completely
    or partially occluding thrombus on a disrupted atherothrombotic
    coronary plaque leading to myocardial ischemia/infarction
-   STEMI
    : Elevated troponin & elevation in ST segment or new LBBB with
    symptoms
    -   \>
        0.1 mV in at least 2 contiguous leads
    -   Exception
        , in V2-V3:
        -   -   \> 0.2
                mV
                in men older than 40 y/o
            -   \> 0.25
                in
                men younger than 40 y/o
            -   \> 0.15
                mV
                in women
-   NSTEMI
    : Evidence of myocardial necrosis (elevated troponin) w/o ST segment
    elevation
-   Unstable
    Angina: Angina without evidence of myocardial necrosis (normal
    troponin)
-   Other
    causes of myocardial injury: coronary spasm, embolism, imbalance of
    oxygen demand and supply 2/2 fever, tachycardia, hypo-/hypertension

Presentation

-   Angina
    or
    Anginal equivalents:
    -   Exertional
        dyspnea, nausea, weakness; and epigastric pain in women and
        diabetics
-   Change
    in patients’ baseline angina, especially onset at rest
-   Physical
    Exam: sinus tachycardia, diaphoresis

Evaluation

-   EKG
    :
    -   Compare
        to prior EKG and assess for
        -   New ST elevations or ST depressions
        -   T
            wave
            inversions: less specific but more concerning if deep (>
            0.3mV)
        -   Biphasic T waves and T wave inversions in leads V2 & V3
            (Wellen’s sign \[LAD\])
-   Cardiac
    biomarkers: troponin I is most sensitive for myocardial injury
    -   ACC
        /AHA guidelines recommend **both** EKG and trop q6 hours
        -   Consider this if high suspicion for primary ACS, despite
            normal initial markers
    -   If
        negative
        x2, stop checking
    -   Can be negative initially; Troponin takes \~2-3 hours to become
        detectable with ischemia

Management

STEMI:

-   STAT page Cardiology on call via Synergy (whether in VA or
    Vanderbilt)
-   ASAP: aspirin 325mg, heparin drip (high nomogram, with bolus)
-   Hold P2Y12 until discussed with Cards fellow, patient may instead be
    taken directly to cath lab and loaded with anti-platelet agent there
    (prasugrel or ticagrelor)
-   Additional
    therapy during hospital stay:
    -   High Intensity statin therapy:  Early initiation of statin in
        ACS reduces risk of short- and long-term coronary events

NSTEMI:

-   Medical
    management with left-heart catheterization within 48 hours of
    presentation.
    -   General
        : bedrest, telemetry, repeat EKG with recurrent chest pain, NPO
        at midnight

-   Anti
    -thrombotic therapy:
    -   Antiplatelet
        agents:
        -   ASA 325 mg loading dose then 81 mg daily after
        -   P2Y12 receptor blocker (can give Plavix (600 mg x1 -> 75 mg
            daily)

-   -   Anti-
        coagulants
        : Unfractionated heparin drip
        -   Type
            this in Epic and select “nursing managed” protocol for “ACS”
        -   VA it can be found under the “Orders” tab along the
            left-hand column.
        -   No adjustment needed for renal function
        -   Enoxaparin
            (LMHW) can be used but requires preserved renal function and
            most interventionalists prefer heparin prior to LHC
        -   Anticoagulation
            can be stopped after catheterization if patient has no
            obstructive CAD, undergoes PCI, or after 48 hours (pure
            medical management)

-   Additional
    therapy: Maximal statin therapy (atorvastatin 80 QD or rosuvastatin
    40mg)

Post ACS Care:

-   DAPT
    : Aspirin 81 mg daily and P2Y12 agent (clopidogrel, ticagrelor,
    prasugrel)
    -   P2Y12
        agent
        determined by cardiology
-   Beta
    blocker in all patients within 24 hours
    -   Metoprolol
        , carvedilol & bisoprolol have proven mortality benefit with
        reduced EF
-   TTE to assess EF
-   ACEi/ARB if anterior STEMI, LVEF \<40%, or CHF
-   Aldo Antagonists if LVEF\<40% with HF symptoms or DM
-   Lipid panel and A1c
-   High intensity statin, consider ezetimibe if LDL > 70
-   Lifestyle Modification: Weight loss, exercise, smoking cessation, in
    DM goal A1c \< 7%
-   Outpatient Cardiology follow up

Additional Information:

-   Initiate
    treatment if there is true concern for ACS, medications can always
    be discontinued
-   TIMI
    score: >2 correlates with
    ↑
    mortality, indicating a need for aggressive treatment
-   Ticagrelor
    and prasugrel are superior for prevention of MI and stroke but have
    an increased bleeding risk, and will delay surgery (CABG) so defer
    to Cardiology to initiate
-   Complications
    :
    -   VT/VF, sinus bradycardia, third-degree heart block, new VSD, LV
        perforation, acute mitral regurgitation, pericarditis and
        cardiogenic shock; More common with STEMI
    -   STEMI
        is usually managed in CCU post-catherization
