# Frailty
 
Functional Status and Frailty

Background

-   Frailty
    : Syndrome of physiological decline in late life, characterized by
    marked vulnerability to adverse health outcomes
-   Functional status: Ability to perform activities necessary in daily
    life (ADL)
-   Pts should be encouraged to exercise as tolerated, with a low
    threshold to refer to PT/OT

Evaluation

-   Order Vitamin D & B-12 levels
-   Vulnerable Elders Scale-13: Identifies community dwelling pts at
    risk for decline over 5 yrs
-   Fried Frailty Tool: Identifies frailty in community dwelling elders
    (1 -2 = prefrail; > 3 = frail)
    -   Fatigue:  are you Fatigued?
    -   Resistance: are you unable to climb a flight of stairs?
    -   Aerobic: are you unbale to walk a block ?
    -   Illness: Do you have more than 5 illnesses ?
    -   Loss: Have you lost more than 5% of weight in 6 months?

​​​​​​​

| 0                                                          | 1                                                                                                                 | 2                                                                              |
|------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| Basic ADL’s                                                | Instrumental ADL’s                                                                                                | Advanced ADL’s                                                                 |
| Feeding Continence Transferring Toileting Dressing Bathing | Using the telephone Shopping Preparing food Housekeeping & Laundry Driving Handling medications Handling finances | Fulfill societal, community and family roles Participate in recreational tasks |

-   
