# Drips
 
MICU/CCU Drips – Blake Funke

-   Most of these have ordersets in Epic, you can choose “Do Not
    Titrate” (used sparingly when initiating on the floor) or “Titration
    Allowed” (to be used in ICU for nurse titration)

| 0                                                 | 1                                                         | 2                                                 | 3                                                                         | 4                                                                           |
|---------------------------------------------------|-----------------------------------------------------------|---------------------------------------------------|---------------------------------------------------------------------------|-----------------------------------------------------------------------------|
| Vasopressors:                                     | Vasopressors:                                             | Vasopressors:                                     | Vasopressors:                                                             | Vasopressors:                                                               |
| Drug                                              | Dose                                                      | Receptors                                         | Indications                                                               | Considerations                                                              |
| Norepinephrine (Levophed)                         | 1 – 100 mcg/min                                           | αα1 \> β1                                         | 1st line septic shock                                                     | Peripheral ischemia, skin necrosis                                          |
| Phenylephrine (Neosynephrine)                     | Bolus: 0.05 – 0.5 mg q 10-15 min Infusion: 40-360 mcg/min | αα1                                               | Used for periprocedural hypotension(Neostick) or pts w/ tachyarrhythmias  | Reflex bradycardia Peripheral ischemia, skin necrosis                       |
| Epinephrine                                       | 1 – 40 mcg/min                                            | αα1=β1=β2                                         | Post PEA arrest Anaphylaxis Septic shock (severe) Cardiac shock           | Tachy-arrhythmias, Peripheral ischemia, skin necrosis                       |
| Vasopressin                                       | 0.04 U/min (no titration); start at NE \> 50              | V1, V2, V3                                        | 2nd line septic shock, Right heart failure                                | Hyponatremia Bradycardia                                                    |
| ANG II \*needs approval by Dr. Rice or Dr. Semler | 20 – 40 ng/kg/min                                         | ANG II                                            | Refractory vasodilatory shock \*typically multiple pressors at high doses | Thrombosis: pt MUST have chemical DVT ppx; contraindicated in heart failure |
| Dopamine                                          | 2 – 20 mcg/kg/min                                         | Dopamine (1-5 mcg) \> β1 (5-10 mcg) \>α1 (>10mcg) | Hypotension Cardiac shock Renal protection                                | Tachy-arrhythmias (↑ risk )) Peripheral ischemia, skin necrosis             |
| Dobutamine                                        | 2.5 – 20 mcg/kg/min                                       | β1 \>\>\> β2                                      | Cardiogenic shock                                                         | Vasodilation Hypotension Tachycardia Tachyphylaxis                          |
| Milrinone                                         | 0.375 – 0.75 mcg/kg/min                                   | PDE-3                                             | Cardiogenic shock                                                         | Hypotension Renally cleared                                                 |

| 0                          | 1                                                      | 2                                                      | 3                                   | 4                                   | 5                      | 6                      | 7                                                         |
|----------------------------|--------------------------------------------------------|--------------------------------------------------------|-------------------------------------|-------------------------------------|------------------------|------------------------|-----------------------------------------------------------|
| Sedatives/Anxiolytics:     | Sedatives/Anxiolytics:                                 | Sedatives/Anxiolytics:                                 | Sedatives/Anxiolytics:              | Sedatives/Anxiolytics:              | Sedatives/Anxiolytics: | Sedatives/Anxiolytics: | Sedatives/Anxiolytics:                                    |
| Drug                       | Drug                                                   | Dose                                                   | Dose                                | Class                               | Class                  | Metabolism             | Side Effects                                              |
| Propofol                   | Infusion: 5 – 150 mcg/kg/min                           | Infusion: 5 – 150 mcg/kg/min                           | General anesthetic (GABA R agonist) | General anesthetic (GABA R agonist) | Hepatic Renal (minor)  | Hepatic Renal (minor)  | Severe Hypotension bradycardia Propofol infusion syndrome |
| Dexmedetomidine (Precedex) | Infusion: 0.1 – 1.5 mcg/kg/h                           | Infusion: 0.1 – 1.5 mcg/kg/h                           | Central αα2 agonist                 | Central αα2 agonist                 | Hepatic                | Hepatic                | Hypotension Bradycardia                                   |
| Midazolam (Versed)         | Push: 0.5 – 5 mg Infusion: 0.25 – 5 mg/h (no max dose) | Push: 0.5 – 5 mg Infusion: 0.25 – 5 mg/h (no max dose) | Benzodiazepine                      | Benzodiazepine                      | Hepatic & Renal        | Hepatic & Renal        | Hypotension                                               |
| Lorazepam (Ativan)         | Push: 0.5 – 10 mg Infusion: 0.5 – 5 mg/h (no max dose) | Push: 0.5 – 10 mg Infusion: 0.5 – 5 mg/h (no max dose) | Benzodiazepine                      | Benzodiazepine                      | Hepatic                | Hepatic                | Hypotension Propylene glycol carrier - AG acidosis        |
| NaN                        | NaN                                                    | NaN                                                    | NaN                                 | NaN                                 | NaN                    | NaN                    | NaN                                                       |

| 0                        | 1                                               | 2             | 3                                                                         |
|--------------------------|-------------------------------------------------|---------------|---------------------------------------------------------------------------|
| Analgesic:               | Analgesic:                                      | Analgesic:    | Analgesic:                                                                |
| Drug                     | Dose                                            | Metabolism    | Side effects                                                              |
| Fentanyl                 | Push: 25 – 100 mcg Infusion: 25 – 400 mcg/h     | Hepatic       | Hypotension, Serotonin syndrome, chest wall rigidity at high doses        |
| Morphine                 | Push: 1 – 5 mg q1-2h prn Infusion: 1 – 5 mg/h   | Hepatic/Renal | Hypotension (profound), itching, constipation, HA; avoid in renal failure |
| Hydromorphone (Dilaudid) | Push: 0.25 – 1 q1-2h prn Infusion: 0.5 – 3 mg/h | Hepatic       | Hypotension, respiratory depression, itching                              |

| 0                 | 1                                                                     | 2                     | 3                                                    | 4                                                               |
|-------------------|-----------------------------------------------------------------------|-----------------------|------------------------------------------------------|-----------------------------------------------------------------|
| Anti-Arrhythmics: | Anti-Arrhythmics:                                                     | Anti-Arrhythmics:     | Anti-Arrhythmics:                                    | Anti-Arrhythmics:                                               |
| Drug              | Dose                                                                  | Indications           | Side effects                                         | Comments                                                        |
| Adenosine         | 6 – 12 mg IV rapid push and flush; may repeat x2                      | PSVT conversion       | Complete AV nodal blockade                           | 10 second half-life Must have continuous EKG/tele monitor       |
| Amiodarone        | ACLS: 300 mg IV push Non-emergent: 150 mg over 10 min then 0.5 mg/min | Vtach/Vfib Afib       | Pulm, ophthalmic and thyroid toxicity w/ chronic use | Less hypotensive effect than other agents Safe in heart failure |
| Diltiazem         | Push: 10 – 20 mg q15 min x 2 if no response Infusion: 5 – 15 mg/h     | Afib Aflutter PSVT    | Bradycardia Hypotension                              | Avoid use in pts with HFrEF                                     |
| Lidocaine         | ACLS: 1 mg/kg x 1 Infusion: 1 – 4 mg/min                              | Vtach                 | Bradycardia Heart block                              | Avoid use in liver failure or heart failure                     |
| Procainamide      | 15 mg/kg over 30 min then 1 – 6 mg/min                                | Vtach Refractory afib | Bradycardia Hypotension                              | Drug-induced lupus Cytopenias                                   |
