# Atrial Fibrillation and Flutter
 
Atrial Fibrillation & Flutter - Benjamin Palmer

Background

-   AF
    : 12-lead EKG with absence of p-waves and irregularly irregular QRS
    complexes
-   Flutter
    : typically sawtooth atrial activity with regular or regularly
    irregular QRS complexe
    -   Look for “sawtooth” waves in inferior leads and V1; ventricular
        rate of \~150 or \~100
-   3 classifications:
    -   Paroxysmal (self-terminating within 7 days)
    -   Persistent (not self-terminating, >7 days)
    -   Permanent (normal rhythm cannot be restored)
-   Rapid ventricular response (RVR) is HR > 100 (ie AFib/Flutter w/
    tachycardia)
    -   RVR is the equivalent to sinus tachycardia in a patient with
        Afib
-   AF/RVR is far more often a consequence of hypotension than the cause
    of it
-   Avoid using antiarrhythmics (including amiodarone) in any pt you
    wouldn’t electrically cardiovert without TEE (e.g. not on
    chronic
    anticoagulation, unknown duration of AFib, possibility of prior
    asymptomatic episodes of AFib)

Evaluation

-   Causes: Mnemonic **“H PIRATES”**
    -   Hypertension
    -   Pneumonia, Pericarditis
    -   Post-op
    -   Ischemia (rare)
    -   Rheumatic Valve
    -   Atrial Myxoma, Accessory Pathway
    -   Thyrotoxicosis
    -   Ethanol, Excess Volume
    -   Sick sinus, sepsis

Management

Inpatient:

-   Always work to address the underlying cause (infection, volume
    overload etc)
-   Rate control is rarely an emergency unless the patient is
    hemodynamically unstable
-   If acute rate control is NOT needed (i.e patient is hemodynamically
    stable), opt for PO meds
-   Treatment goals:
    -   Rate control, Goal HR \< 110
    -   Anticoagulation
    -   Rhythm Control (if indicated)
-   Rate control
    :
    -   β
        -blockers (Metoprolol), calcium channel blockers (Diltiazem),
        Digoxin, Amiodarone
        -   -   Before administering any nodal blocking agents be wary
                of WPW/pre-excitation
            -   AV-node blocking in this setting can accelerate A-V
                conduction and
                
                VT/VF
            -   Would use procainamide in those situations
-   HFrEF: low dose PO metoprolol provided pt is warm and well :perfused
    -   -   Avoid CCB
        -   Consider discussion with Cardiology for Digoxin or
            Amiodarone
-   If acute rate control needed, consider IV metoprolol 5mg x1 or IV
    diltiazem 15-20mg x1, must follow with maintenance therapy (See
    acute tachyarrhythmia section above)
-   Anticoagulation (AC):
    -   If new onset a-fib and cardioversion is anticipated, begin AC as
        soon as possible, Lovenox > heparin drip initially, DOAC would
        also be acceptable
    -   If new onset a-fib but no immediate plans for cardioversion, AC
        should be considered based off of CHA2DS2-VASc
        -   -   AC in this setting is not an emergency
    -   If arrhythmia persists >48 hours, AC should be initiated if
        indicated
    -   If known a-fib continue his or her AC while inpatient
    -   If procedures/surgery is anticipated, bridging AC w/ heparin or
        LMWH should be decided on a case-by-case basis, likely not
        indicated with low stroke risk
-   Rhythm
    Control:
    -   New onset a-fib (first time diagnosis): most pts will be a
        candidate for trial of electrical cardioversion
        -   -   If onset clearly within 48 hours, can proceed without
                TEE
            -   If onset >48 hours, will need TEE to rule out LAA
                thrombus
            -   If cardioversion is anticipated or performed, pts need
                AC for at least one month
    -   If typical flutter, consider EP consult as ablation can be
        quickly and safely performed
    -   If hemodynamically unstable, HFrEF, or highly symptomatic a-fib,
        should be considered for rhythm control strategies (options
        include class 1c agents (Flecainide) and class III agents
        (amiodarone, sotalol, dofetilide) ​​​​​​​

Outpatient

:

-   Rate
    control typically achieved with beta blocker therapy, metoprolol is
    most frequently used and can be converted to once daily dosing with
    metoprolol succinate
-   AC
    pending CHA2DS2-VASc scoring; DOACs are typically the agents of
    choice
    -   Warfarin indicated in valvular afib (AF 2/2 mitral stenosis)
-   Rhythm
    control is a complex decision, consider EP referral
    -   If highly symptomatic or HFrEF, consider ablation vs
        pharmacologic rhythm control
-   Serial
    monitoring for risks/benefits of AC and tachycardia induced
    cardiomyopathy
