# Hypoglycemia
 
Hypoglycemia – Will Bassett

Background

-   Definition
    : BG \<70 mg/dL on any measurement
    -   -   -   Generally worse outcomes than hyperglycemia
            -   Causes:

    -   Inflammation
        -   Sudden
            blood glucose drops in previously well controlled patient
            may indicate a new inflammatory process (infection,
            pancreatitis, sepsis etc.)
        -   Check vitals and assess for new symptoms

    -   Iatrogenic (insulin dose not adjusted for AKI or NPO)
        -   Can
            consider
            reduction of basal insulin and/or consider holding prandial
            insulin
        -   If
            patient
            is NPO, consider maintenance D5W/D5LR infusion
-   If
    patient
    is NPO, schedule blood glucose checks at a regular interval ​​​​​​
    Can present with Sudden tremor, palpitations, delirium, dizziness,
    AMS

Management

-   Give PO carbohydrate load (15-20g oral glucose) if pt is alert and
    tolerates PO
-   Repeat measurement after 15 minutes and treat again as needed
-   Give IV D50 if severe (\<50), or cannot take PO
-   Give glucagon 0.5-1mg SQ/IM if no IV access and impaired
    consciousness
    -   Effect is transient and IV access should be obtained ASAP for
        glucose infusion
-   Do NOT hold basal for T1DM: treat the low, then reduce dose if
    needed (not necessary if low caused by high mealtime or SSI). In
    general, doses need not be reduced by > 30%
