# Interns' Guide to Rotations at VA
 
VA: Veterans Affairs Rotations

Always make sure that your VA login works a few days before you are
scheduled to start!

**Conference Schedule**

VA Morning Report: Mon-Tues-Wed-Fri (just like VU except Tuesday also
has CXR rounds)

Noon Conference – Mon, Wed & Friday on 7T; 12:00 – 1:00: Lunch with
various lectures.

Fox and Hedgehog – Light Hall 208; Tuesdays 12:00 – 1:00; Chief Resident
Conference

**VA General Wards (1A – 6B)**

-   **Team** : 1 Res, 2 Interns with patient cap of 8 each (16 total)
-   Pick up list 6:30 AM; Admit every other day; Can sign-out on
    non-admit days at 2 PM
-   **Rounds** alternates at 7 AM on admitting days, 8 AM on
    non-admitting days, meet at workrooms
    -   Workroom:
        -   Teams 1-3 on 2N
        -   Team 4 at 2nd floor main elevators
        -   Team 5 on 3N
        -   Team 6 2nd floor off ICU hallway
-   **Conferences** : VA Morning Report; Noon conference, Fox; don’t
    forget CXR rounds on Tuesdays!
-   **Review** : Many admissions for falls (review Geriatrics sections),
    chest pain, ACS/NSTEMI, syncope (review cardiology), COPD
    exacerbation, Pneumonia (ID), Skin and Soft Tissue Infections (ID),
    diabetic foot infections.
-   **Tips** : Admission days can be very busy and anything you can get
    done on the non-admitting days will make your life easier
    (especially DIPNs for people leaving the next day); start your own
    patient list in a word document to use as your pre-rounding sheet as
    well as sign-out; Roll your pagers via Vanderbilt operator (same as
    at VU); ensure all orders on patients still in the ED are “Delayed”
    or they will disappear once on the floor (ask your resident); All
    consults must be accompanied by page to the covering fellow (see
    synergy for medicine subspecialties, TVHS website for surgery/other)

**VA MICU**

-   Team: 3 Res, 3 Interns, no specific patient cap (typically 10-12)
-   Day Intern: 7 AM - 9 PM; Night Intern 8 PM - 10 AM; MICU is on 2nd
    floor between 2N and 2G
    -   Night intern presents the old patients on morning rounds
-   Excused from Conferences
-   **Review** : ARDS, Vent Settings, Modes of Oxygen Delivery, Sepsis,
    Management of Shock, MICU/CCU Drips, Basics of blood gases (Pulm)
    Stress Dose Steroids (Endo), Cirrhosis (Hep)
-   **Tips** : Night intern presents all of the old patients in the
    morning and signs the notes. The day intern owns the A&P of the
    notes by keeping them updated. Never hesitate to relay information
    to your resident overnight if you are concerned

**VA Nights**

-   **Team** : 1 Res, 2 Interns, total of 10 admissions overnight
-   Start at 7 PM, Admit until 5:30 AM, present new patients to teams at
    7 AM, leave by 8 AM
-   **Start on Sunday night** ; Off day is Saturday night for interns
-   **Tips** : Admissions typically bolus at the start of shift and stop
    later in the night, so worry about seeing patients, formulating
    plans with resident and putting in orders as the notes can be
    finished once it slows downs; the cafeteria at VU closes at 2 AM;
    communicate everything you do with your resident who is supervising
    a second intern as well; ensure all orders on patients still in the
    ED are “Delayed” or they will disappear once on the floor (ask your
    resident)
