# Hemoptysis
 
| 0                        |
|--------------------------|
| Hemoptysis – Henry Brems |

Background

-   Distinguish between massive (>600cc/24hr or >100cc/hr) and
    non-massive hemoptysis; however, due to practical difficulties
    quantifying expectorated blood and limitations in quantifying blood
    in lungs that is not expectorated, verbiage is falling out of favor
-   Massive is potentially life-threatening due to impaired ventilation
    not necessarily due to hemodynamic compromise
-   Remember UGIB (hematemesis) and nasopharyngeal bleeds can easily
    mimic hemoptysis and require different management
-   Presentation based on source of bleed:

| 0                     | 1                                                                                                       |
|-----------------------|---------------------------------------------------------------------------------------------------------|
| Structure             | Etiologies                                                                                              |
| Airways               | Bronchitis (common cause of non-massive), bronchiectasis (especially in CF pts), neoplasm               |
| Alveolar/ Parenchymal | Infectious (bacterial PNA, abscess, TB, fungal, aspergilloma), Rheumatic (Goodpasture’s, GPA, Behcet’s) |
| Vascular              | PE, AVM, CHF, mitral stenosis                                                                           |
| Other                 | Coagulopathy, traumatic, foreign-body, iatrogenic, cocaine-induced                                      |

Evaluation

-   Assess anticoagulation status
-   Labs: CBC, BMP, Coags, UA (for hematuria), ABG (evaluate
    oxygenation), type and screen
    -   Also consider ANA, ANCA, Anti-GBM, sputum culture (bacteria,
        fungal, AFB), sputum cytology as indicated to further evaluate
        etiology
-   Imaging: CXR first (to evaluate etiology and to localize the source
    to a side). May likely require Chest CT pending prior workup,
    severity of bleed, and stability of patient
-   Bronchoscopy is sometimes indicated to localize bleeding source  

Management

-   Hemoptysis that is non-massive and does not impair ventilation can
    generally be evaluated and treated non-urgently
-   Urgent evaluation needed if there is any hemodynamic compromise,
    hypoxia, hypercarbia, or respiratory distress
-   Reverse underlying coagulopathy if present. Consider trending HCT
-   Make NPO
-   If unilateral bleed, place **bleeding lung down** (i.e. if the
    source is left lung, place pt on left side) to prevent filling
    'good' lung with blood ( **Include this info in sign-out** if known)
-   Ensure a secure airway: Massive hemoptysis may require intubation
    and MICU transfer
-   Urgent pulmonary consult if clinical instability: Bronchoscopy is
    diagnostic and therapeutic
-   Obtain CT Bronchial Artery Protocol if concern for bronchial artery
    source (especially in CF patients) so embolization can be planned
    -   Order this at VUMC with a CTA Chest (NOT a CTA PE as that will
        be timed incorrectly) and include "bronchial artery protocol" in
        comments for the study
-   Consider IR consult for angiography as diagnostic and therapeutic
    option
    -   Consult early if there is massive hemoptysis; If bronchoscopy is
        attempted but fails to stop the bleed, they can get to
        angiography fastest if IR has already been made aware
-   Consider GI and/or ENT evaluation if source of bleed is unclear
