# Coagulopathies
 
Coagulopathies – Jason Jones

-   If you have a pt with pathological bleeding, first determine
    **platelet vs coagulation** disorder
-   Platelet Disorders: Skin/Mucous membrane bleeding; Petechiae; Often
    mild bleeding following surgery and tends to immediately follow
    surgery
-   Coagulation defect: Bleeding deep in soft tissues (muscles/joints);
    hemarthroses, hematomas; Tend to have delayed bleeding after surgery
    that can be severe
    -   Coagulopathies can be divided into **Hereditary** vs
        **Acquired** causes

Hereditary

Hemophilia A (Factor VIII Deficiency) and Hemophilia B (Factor IX
Deficiency)

-   Inherited in X-linked Recessive pattern
-   Diagnosis: Isolated prolonged PTT with normalization upon mixing
    study
-   Management
    : purified/recombinant Factor VIII or IX. Desmopressin for mild
    disease
-   If you have patient with hemophilia who needs a procedure/surgery or
    is acutely ill, this requires consult to benign hematology  

von Willebrand Disease (vWD)

-   Can be hereditary (common) or acquired
-   Abnormal quantity or function of von Willebrand Factor (vWF) needed
    for platelet function
-   Type 1 (most common): Quantitative defect. Low quantity, normal
    function of vWF
-   Type 2: Qualitative defect. Normal quantity, abnormal function of
    vWF. In Type 2A, large multimer formation is impaired
-   Type 3 (rarest): Complete absence of vWF
    
    phenotypically similar to hemophilia A
-   Order in Epic: vW Profile = vWF Ag, Factor VIII Activity, Ristocetin
    Cofactor Activity
-   Management
    : Desmopressin (DDAVP) can be useful as prophylaxis or treatment

Acquired

Coagulation Factor Inhibitors

-   Associated with autoimmune disease (paraneoplastic vs. autoantibody)
-   Seen in hemophilia due to frequent treatments with recombinant
    factors (alloantibody)
-   Diagnosis: Elevated PTT that does not normalize with mixing study
-   Management
    : Immunosuppression with steroids; cyclophosphamide +/- rituximab
    -   Consult
        Hematology early (rare disorder with major bleeding
        complications)

Vitamin K Deficiency

-   Caused by malnutrition, liver disease, or iatrogenic with warfarin
-   Causes deficiency of Vit K dependent coagulation factors (Factors
    II, VII, IX, X)
-   Diagnosis: elevated PT, if severe may have prolonged PTT as well
-   Vitamin K deficiency will correct in the lab in a mixing study
-   Management
    : Replace vitamin K, see "Transfusion" section for more details
