# Thrombocytopenia
 
Thrombocytopenia – Robert Dunn

Background

-   Platelet
    count \<150 k/µL (mild), 50-100 k/µL (moderate), \<50 k/µL (severe)
-   Framework for differential: Platelet
    Consumption, sequestration, or destruction
-   Causes
    to consider:
    -   Can’t Miss Diagnoses: TTP, HUS, HELLP, DIC, HIT
    -   Splenomegaly can represent: Plt sequestration, cirrhosis, portal
        hypertension
    -   Drug-induced: (
        Antibiotics, heparin, chemo, GpIIb/IIIa antagonists,
        H2-antagonists)
    -   Rheumatologic cause – SLE and sarcoidosis
    -   Sepsis, independent of DIC
    -   Immune thrombocytopenia (ITP) is a diagnosis of exclusion
    -   Massive physiologic consumption: large hematoma, active
        hemorrhage
    -   Cirrhosis – results in low thrombopoietin (TPO)
    -   Chronic alcohol use – direct marrow suppression
    -   Infections: HIV, HCV, EBV, Parvovirus, Rickettsia, H. pylori
    -   Bone marrow failure: aplastic anemia, MDS, leukemia,
        chemotherapy
    -   Dilutional: fluid resuscitation and massive transfusion
    -   Platelet clumping (lab artifact)

Presentation

-   Petechiae
    (lower legs typical site; in mouth = wet purpura)
-   Overt bleeding,
    mucosal bleeding, epistaxis (seen when \<20 k/µL ),
    Splenomegaly

Evaluation

-   CMP, CBC w/diff, peripheral smear, citrated platelet count, immature
    patelet fraction (IPF)
-   LDH, Fibrinogen, PT/aPTT
-   Determine timing of decline
    -   Look
        at other cell lines - never normal to have two cytopenia’s
    -   Review
        recent initiation of drugs: (heparin, antibiotics, and
        chemotherapy)
-   Consider abdominal ultrasound to look for splenomegaly and liver
    pathology
-   Infectious work up (HIV, HCV)
-   Calculate 4T Score and consider your pretest probability for HIT
    testing
    -   HIT
        Ab: ELISA is first test – only run once/day at VUMC so order
        early if considering
    -   Reflex Serotonin release assay (SRA) for confirmation

Management

-   Plt
    \<50k
    -   Discontinue pharmacologic DVT prophylaxis
    -   If on anticoagulation
        : consider risk/benefits of continued anticoagulation
        -   Can
            transfuse plt’s if AC is mandatory
-   Plt
    \<10k
    -   Transfuse
        platelets given risk of spontaneous intracranial hemorrhage
    -   In pt’s with HIT or TTP, there is theoretical concern that
        transfusing plt can “fuel the fire”
        and lead to more thrombosis
        -   Therefore,
            bleeding with HIT or TTP, discuss with Hematology before
            transfusion
-   HIT
    -   If pretest probability is high or HIT is confirmed
    -   Stop Unfractionated and low molecular weight heparin products
    -   Start Argatroban gtt
-   If schistocytes present on peripheral smear = TTP
    -   Contact Nephrology and Hematology for PLEX

Additional Information

-   Clumping on lab draws:
    -   Obtain Citrated platelet (“blue top” tube – CPRS refers to it as
        a blue top platelet count)

<!-- -->

-   If
    no
    resolution, obtain a "Gold top" LAB 301 in Epic (Named: Plt count)
