# Biliary Disease
 
Biliary Disease – Alex Wiles

Pearls:

-   ERCP
    is not available **at VA** : requires fee-basis consult to VUMC,
    contact GI to arrange
    -   Prior cholecystectomy
        
        CBD normally dilates to 10 mm, not pathologic
    -   Expect some CBD dilation after stent placement, pneuomobilia
        often occurs as well
    -   CBD dilation classically > 6mm, but CBD dilates with age: 70 yo
        
        7mm, 80 yo
        
        8mm; opiates can also cause biliary dilatation
    -   CT has low sensitivity for stones, so get the RUQ U/S

Biliary Colic

-   Transient biliary obstruction typically at the GB neck without GB
    inflammation (no fever)
-   Presentation: Constant (not colicky) intense, dull RUQ pain and N/V
    for 30 minutes to 6 hours, then resolves, provoked by fatty foods
    (CCK), absent Murphy’s sign
    -   Evaluation: Normal (CBC, LFTs, Lipase, Lactate)
-   Imaging: RUQ U/S: cholelithiasis (stones in GB)
    -   Management: Elective cholecystectomy as outpatient

Acute Calculous Cholecystitis

-   
-   Inflammation of the GB (obstructing stone in the GB neck or cystic
    duct)
-   Ddx: PUD, pancreatitis, choledocholithiasis, ascending cholangitis,
    IBD, Fitz-Hugh Curtis
-   Presentation: Severe constant RUQ pain, fever/chills, N/V, + Murphy
    sign
-   Evaluation: CBC (leukocytosis), CMP (mild AST/ALT
    ↑
    , nL bili), Lipase, Lactate, BCx x2
-   Imaging: RUQ U/S: gallstones + GB wall thickening or pericholecystic
    edema
    -   If U/S non-diagnostic (no stones or GB inflammation)
        
        HIDA Scan (lack of GB filling)

Management: NPO, IVF, IV Abx until resolved or surgical removal

-   
-   Urgent Cholecystectomy (\<72H) with EGS;
    -   If poor surgical candidate: Cholecystostomy with IR; endoscopic
        drainage options for selected patients (i.e. poor surgical
        candidates also with ascites)
    -   Complications: gangrenous cholecystitis, perforation,
        emphysematous cholecystitis, chole-cysto-enteric fistula,
        gallstone ileus

Acute Acalculous Cholecystitis:

-   
-   Inflammation of the GB without obstructing stone (due to stasis and
    ischemia)
-   Presentation: Seen in critically ill/ICU pts; similar history as
    above; may present as unexplained fever or RUQ mass (rarely
    jaundice)
-   Ddx: calculous cholecystitis, pancreatitis, hepatic abscess
-   Evaluation: Same as acute calculous cholecystitis
-   Imaging: GB wall thickening, pericholecystic edema, intramural gas,
    GB distention

Management: Supportive care, antibiotics, GB drainage

-   
-   IVF, correct electrolyte abnormalities, NPO
-   Broad spectrum antibiotic coverage
-   Place CT-guided procedure consult for cholecystostomy placement
-   Consult EGS if necrosis, perforation, or emphysematous changes
    present

Choledocholithiasis:

-   
-   Obstruction of biliary outflow by CBD stone without inflammation (no
    fever)
    -   Impacted cystic duct stone (cholecystitis) or compressing CBD
        (Mirizzi syndrome)
-   Presentation: RUQ pain (can be painless), N/V and jaundice
-   Evaluation: CMP and D-bili (Bili/ALP/ GGT
    ↑↑↑
    , AST/ALT mild
    ↑
    ), CBC (Leukocytosis suggests cholangitis), Lipase
-   Imaging: RUQ U/S: dilated CBD (ULN is 6mm)
    
    MRCP/EUS vs ERCP (see below)
    -   MRCP preferred given non-invasive but has lower sensitivity for
        smaller stones (consider EUS if still have suspicion despite
        negative MRCP)

Management

-   
-   NPO & IVF, pain control PRN
-   Guidelines recommend use of RUQ U/S and LFTs to help decide on MRCP
    vs ERCP based on likelihood of CBD stone.  You must be confident
    there is a CBD stone prior to ERCP given risks associated with
    procedure
-   High Risk: presence of any of the three following criteria
    
    consider urgent ERCP
    -   CBD stone seen on imaging
    -   Ascending Cholangitis
    -   TBili > 4 **AND** CBD dilation (> 6 mm, unless prior
        cholecystectomy or elderly)
        -   Intermediate Risk: warrants further evaluation with either
            MRCP or EUS prior to ERCP or cholecystectomy with
            intraoperative cholangiogram (obtain MRCP if overnight,
            discuss with GI fellow)
            -   CBD Dilation; Age > 55
            -   Abnormal liver enzymes (CBD stone can cause any pattern
                of LFT abnormalities)
        -   Low Risk: for patients with symptomatic cholelithiasis and
            no risk factors as above; no further evaluation required,
            can go to cholecystectomy <u>+</u> IOC

Acute Cholangitis:

-   
-   Bacterial infection of biliary tract 2/2 obstruction or prior
    instrumentation (ERCP)
-   In ERCP-naïve pts, this is typically in setting of
    choledocholithiasis
-   Pts with malignant obstruction typically do not develop cholangitis
-   Presentation: Charcot triad (RUQ P, F/C, Jaundice); Reynolds’ Pentad
    (AMS, Hypotension)
-   Evaluation: CBC, CMP (D bili, ALP
    ↑↑↑
    ) Blood Cultures, Lipase, Lactate
    -   CRP, AST/ALT can be
        ↑↑
        as well
-   Imaging: RUQ U/S: dilated CBD (ULN is 6mm), no need for MRCP/EUS
    -   Consider MRCP overnight if ERCP is not being done emergently

Management: NPO, IVF, IV Abx; Consult GI for urgent ERCP (generally
within 24 hr)

-   
-   If ERCP not feasible or fails to establish biliary drainage, can
    consider EUS-guided biliary drainage, percutaneous transhepatic
    cholangiography, or surgical decompression
-   
-   Antibiotics for Biliary Disease (IDSA Guidelines):
    -   Mild to moderate acute cholecystitis (stable):
        -   Ceftriaxone 2g daily, Cefazolin 1-2g q8H
    -   Cholangitis or Severe acute cholecystitis (unstable or
        immunocompromised):
        -   Covering for GNRs and Anaerobes; 3 options:
            -   Zosyn 3.375g q8H, Meropenem 1g q8H or Cipro 500 q12H and
                Flagyl 500 q8H
            -   Healthcare-associated Biliary infections: consider
                Vancomycin (order w/ PK consult)
