# Hypertension
 
Hypertension (HTN) – Jonathan Davis

Background

-   #SBP >20 or #DBP >10 doubles risk of stroke and CVD
-   Prevalence \~45% with new cutoff (≥130/80); control achieved in
    \~50%
-   Definitions
    -   Resistant HTN:
        Uncontrolled BP despite taking 3 antihypertensive medications
        including a diuretic, OR 4 total medications
    -   Whitecoat HTN
        :  Mean BPs lower than threshold of HTN based upon out-of-office
        measurements (falsely elevated measurements during visits). If
        SBP > 130 but \< 160, consider screening for white coat HTN with
        home monitoring
    -   Masked HTN
        : Mean BP at/above threshold for hypertension based upon
        out-of-office measurements (falsely decreased measurements
        during visits). If office SBPs consistently 120-129 consider
        screening for masked HTN with home monitoring
-   Diagnosis
    -   Requires ≥2 elevated pressures on ≥2 occasions
        -   Home and ambulatory BP monitoring recommended to confirm
            diagnosis
        -   Ideally, measurements with legs uncrossed, arm at level of
            heart, after 5 minutes of rest and with empty bladder; avoid
            caffeine or tobacco 30 minutes prior
        -   Screening
    -   Grade A USPTF rec: Screen all adults >18. Screen adults at least
        semiannually if have risk factors for HTN (obesity, AA), or if
        previously measured SBP 120-129

| 0                                                 | 1                                                 |
|---------------------------------------------------|---------------------------------------------------|
| ACA-AHA guidelines (2017) (based on SPRINT trial) | ACA-AHA guidelines (2017) (based on SPRINT trial) |
| Normal                                            | \<120/80 mmHg                                     |
| Elevated BP                                       | systolic 120-129 mmHg AND diastolic \<80 mmHg     |
| Stage 1                                           | systolic 130-139 mmHg OR diastolic 80-89 mmHg     |
| Stage 2                                           | systolic ≥140 mmHg OR diastolic ≥90 mmHg          |

Evaluation

-   BMP, CBC, lipid panel, UA, TSH, EKG. Consider additional testing
    including TTE, urine Alb:Cr ratio, or uric acid.
-   Distinguish between primary (90% incidence) and secondary HTN (10%):
    -   Suspect 1º if gradual onset, family hx, associated with weight
        gain & lifestyle factors
    -   Suspect 2º if early onset (\< 30yo), late onset (> 65 y/o),
        abrupt onset, disproportionate end-organ damage, resistant HTN
-   Uncommon causes: Pheochromocytoma, Cushing’s syndrome, thyroid
    dysfunction, aortic coarctation, primary hyperparathyroidism,
    acromegaly, congenital adrenal hyperplasia

| 0                                 | 1                                                              | 2                                                       |
|-----------------------------------|----------------------------------------------------------------|---------------------------------------------------------|
| Common 2o Causes                  | Suggestive Feature                                             | Diagnostic Testing                                      |
| Primary Kidney Disease            | Hypervolemia, ↑ Cr, abnormal UA, fhx of PKD                    | UA, Urine Alb:Cr ratio, Renal US                        |
| Renovascular disease (RAS or FMD) | Renal bruit, ↑ Cr after ACE-I or ARB, young age                | Doppler renal US                                        |
| OSA                               | Apneic events, somnolence, obesity                             | Polysomnography                                         |
| Primary Hyperaldosteronism        | Hypokalemia, metabolic alkalosis, resistant HTN, etc.          | Start with plasma aldosterone/renin levels              |
| Drug or Alcohol Induced           | Hx of substance use (cocaine, caffeine, nicotine, medications) | UDS, BP improvement after withdrawal of suspected agent |

Management

-   JNC 8 recommends treating to a **goal BP \<140/90** in all pts \< 60
-   Consider intervenable contributing factors:
    -   Obesity
        , High Na diet (canned foods, fast foods, processed meats)
    -   Excess
        alcohol intake
    -   Medications (e.g., NSAIDs, decongestants, MAOs, clonidine
        withdrawal, cyclosporine, steroids)
    -   Substance use (e.g., caffeine, cocaine, amphetamines)  
-   Lifestyle interventions (first line for any stage of elevated BP):
    -   8-14 mmHg
        ↓
        :
        DASH diet (fresh produce, whole grains, low-fat dairy)
    -   5-10 mmHg
        ↓
        :
        Weight loss (10 kg or 22 lbs), expect 1mm Hg for every 1kg
        reduction in body weight
    -   3-9 mmHg
        ↓
        :
        Na+ restriction (1.5 g / day), aerobic exercise for 90-150
        min/week, increased intake of K+ rich foods
    -   2-4 mmHg
        ↓
        :
        Moderate EtOH (2 drinks/day for men; 1 drink/day for women)  
-   Medications (See table below):
    -   Initiate pharmacological therapy with Hypertension Stage I
        (ACC/AHA guideline) and ASCVD score > 10% or Stage II pts
        (regardless of ASCVD score)
    -   Use
        first
        line agents from the following classes
        -   ACE-I or ARB
        -   Thiazide
            Diuretics (preferred in AAs)
        -   Dihydropyridines
            CCB (preferred in AAs)

Additional Information

VA Specific Guidance:

https://www.healthquality.va.gov/guidelines/CD/htn/

-   Preferred Agents/Agents that **don’t require PADR** :
    -   Diuretics – Any
    -   ACEIs – Lisinopril, Benazepril, Enalapril, Ramipril, Captopril
    -   ARBs – Losartan, Valsartan
    -   Beta Blockers – Carvedilol, Metoprolol tartrate/succinate,
        atenolol, propranolol
    -   DHP – Amlodipine
    -   Non-DHTs – Verapamil, Diltiazem
    -   Aldosterone
        Receptor Antagonist – Spironolactone
    -   Alpha1 Antagonist – Doxazosin, Prazosin, Terazosin
    -   Direct
        Acting Vasodilators – Minoxidil, Hydralazine
    -   Alpha2 Agonist – Clonidine tablet, methyldopa
-   Agents
    that **require PADR** :
    -   ACEIs - Quinapril
    -   ARBs – Candesartan, Irbesartan, Olmesartan, Telmisartan
    -   Beta blockers – Labetalol, Nebivolol
    -   DHP – Nifedipine SA
    -   Aldosterone Receptor Antagonist – Eplerenone
    -   Alpha2 Agonist – Clonidine patch
-   How
    to get BP cuff at the VA
    -   Consult
        tab: New Consult
        →
        Select Campus
        →
        Select Inpatient or Outpatient
        →
        Prosthetics Main
    -   Consult Menu
        →
        Select Y/N for requirement of discharge
        →
        BP Cuff TVH
    -   \*Must answer all questions in the consult, including blood
        pressure cuff size.

Cost:

-   Publix: Free (amlodipine, lisinopril), $7.50 x 90 days (losartan,
    metoprolol tartrate, HCTZ)
-   Walmart: $4/month (amlodipine, carvedilol, enalapril, hydralazine,
    HCTZ, irbesartan, lisinopril, losartan, ramipril)

| 0                                           | 1                                                                                                                                                     | 2                                                                                                                                                          |
|---------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Drug Class                                  | Common Drugs                                                                                                                                          | Side effects/ comments                                                                                                                                     |
| Thiazide diuretics                          | HCTZ 12.5-50 mg Chlorthalidone 12.5-25 mg (Preferred agent based on RCT evidence)                                                                     | \- HypoNa, HypoMg, HypoK, increased uric acid, hypovolemia, orthostatic hypotension Ok to use in pregnancy per ACOG (2019), but considered 2nd or 3rd line |
| ACE-I                                       | Lisinopril, benazepril, fosinopril, quinapril (all 5-40 mg daily) Ramipril, 2.5-20 mg in 1-2 doses                                                    | -Angioedema (more common in AA) AKI, hyperkalemia, cough -Don’t use with ARB -Contraindicated in pregnancy                                                 |
| ARBs                                        | Losartan 25-100 mg in 1-2 doses Candesartan 8-32 mg in 1-2 doses Irbesartan 150-300 mg Valsartan 80-320 mg                                            | -AKI, hyperkalemia -Angioedema (less frequent than ACE-I) -Don’t combine with ACE-I -Contraindicated in pregnancy                                          |
| CCB                                         | Dihydropyridine: Amlodipine 2.5-10 mg 1-2 doses Nifedipine 30-120 mg in 1-2 doses Nondihydropyridine: Diltiazem ER 120-480 mg Verapamil ER 100-480 mg | Dihydropyridine: -Peripheral edema -Worsening proteinuria Nondihydropyridine: -Constipation -Heart block if used with BB -Contraindicated in HFrEF         |
| Aldosterone receptor antagonists            | Spironolactone 12.5-50 mg Eplerenone 25-50 mg                                                                                                         | -Good choice for resistant HTN -AKI, hyperkalemia -Spironolactone—gynecomastia & sexual side effects -Contraindicated in pregnancy                         |
| BB                                          | Carvedilol 6.25-25 mg bid Metoprolol succinate 25-200 mg qd Nebivolol 5-10 mg Labetalol 100-300 bid                                                   | Reserve for CHF/CAD -Hyperglycemia, fatigue, ↓ HR β 1-selective may be safer in pts with COPD, asthma, diabetes                                            |
| Vasodilators                                | Hydralazine 25-100 mg bid or tid Minoxidil 5-10 mg                                                                                                    | Reflex tachycardia, fluid retention                                                                                                                        |
| Centrally- acting agents (alpha 2 agonists) | Clonidine 0.1-0.2 qd, (Weekly transdermal patch is preferred to avoid non- compliance and subsequent reflex HTN) Methyldopa 250-500 mg qd             | Rebound hypertension, withdrawal Reserved for resistant hypertension due to unfavorable side effect profile                                                |

| 0                           | 1                                                           |
|-----------------------------|-------------------------------------------------------------|
| Conditions                  | Drug Class                                                  |
| Heart failure               | ACE-I/ARB or ARNI + BB + spironolactone + diuretics         |
| CAD                         | ACE-I or BB                                                 |
| Diabetes                    | All first line agents, ACE-I/ARB if presence of albuminuria |
| CKD                         | ACE-I/ARB                                                   |
| Recurrent stroke prevention | ACE-I, thiazide diuretic                                    |
| Pregnancy                   | Labetalol (first-line), nifedipine, methyldopa, hydralazine |
