# PE
 
Pulmonary Embolism – Nick Pietrini

Background

-   A thrombus or “clot” originating in a deep vein (LE > UE) embolizing
    to the pulmonary arterial circulation
-   Virchow’s
    triad: stasis (immobilization, travel), hypercoagulable state
    (cancer), injury to endothelium (surgery, trauma). Idiopathic
    possible but 12% of idiopathic will be diagnosed with cancer within
    a year.
-   Genetic
    : Factor V Leiden, prothrombin gene mutation, protein C/S
    deficiency, antithrombin III deficiency
    -   Acquired
        : antiphospholipid syndrome, cancer, myeloproliferative
        disorders, nephrotic syndrome, OCPs
-   Classification (requires TTE):
    -   Low risk:
        Hemodynamically Stable without RV strain or myocardial necrosis
    -   Submassive:
        Hemodynamically stable with RV strain and/or myocardial necrosis
        -   -   RV strain seen on TTE (“D-sign”), BNP >150
            -   Myocardial necrosis with troponin >0.05
    -   Massive:
        Sustained hypotension and/or concerns for shock

Presentation

-   Dyspnea / Tachypnea – most common, can be only exertional
-   Tachycardia – common, sometimes the only finding
-   Chest pain – usually pleuritic
-   Hemoptysis
-   Lower extremity pain / swelling – occurs in 50% of pts with DVT
-   RV Failure (large PE) – elevated JVP, hypotension, syncope

Evaluation

-   EKG: most commonly sinus tachycardia
    -   Less
        commonly and indicative of large PE: Right axis deviation, RVH,
        RBBB, RA enlargement, S1Q3T3 (deep S in lead I, deep Q and
        inverted T in lead III), TWI in V1-V3 (most common finding
        reflecting severity)
-   CXR (typically normal)
-   Subtle
    abnormalities: linear atelectasis, pleural effusion, PA cutoff sign

<!-- -->

-   ABG: usually with hypoxia, hypocapnia, high A-a gradient
-   Troponin: increases in 30-50% of pts with moderate to large PE
    associated with RV strain
-   BNP: often increases with large PE (but less so than in HF patients)
-   D-Dimer\*: If low pre-test probability (based on Wells criteria)
-   CTA Chest PE protocol; NPV 95-99%
    -   Helps
        identify potential alternative diagnoses as well as determine
        severity of PE
-   V/Q scan: Useful when CXR is normal, no severe cardiopulmonary
    abnormalities, and contraindication to contrast (ie AKI)
-   Lower extremity dopplers
-   TTE: differentiate submassive vs low risk, chronic right sided
    failure (PAP>50 chronic)

Management

Acute:

-   ABCs: Provide necessary respiratory and hemodynamic support
-   Initial AC:  If PE is highly probable (Wells score > 6) or
    moderately probable (Wells between 2-6, but workup will take > 4
    hours) and bleeding risk is low, empirically start IV heparin drip,
    then establish a definitive diagnosis as per above (CTA PE).
    -   IV heparin drip (EPIC order set): bolus (80 un/kg), then drip
        starting 18 unit/kg
    -   Enoxaparin (Lovenox): 1 mg/kg subQ q12h (\*avoid in ESRD)
-   Thrombolytics (tPA): Most effective within 24 hours, but effective
    up to 14 days. Use 100 mg of tPA over 2 hours, then resume heparin
    gtt. Attending/fellow level decision.
-   Indications:
    -   -   Massive PE: PE causing hypotension (shock)
        -   Refractory hypoxia or respiratory failure requiring
            mechanical ventilation.
        -   RV failure clinically or on echo (relative indication if not
            shock)

<!-- -->

-   IVC filter (very uncommon): AC is contraindicated, bleeding risk
    unacceptably high, recurrent PE despite optimal AC
-   Embolectomy: Catheter-directed or surgical
    -   Indicated for pt with submassive PE, pts with massive PE in whom
        thrombolytic therapy is contraindicated, or when thrombolytic
        therapy has failed

Chronic:

-   Long-term AC (DOAC is the mainstay of management)
    -   Apixaban (Eliquis): 10 mg BID x7 days
        à
        5 mg BID
        -   -   Can use in renal failure (do not dose reduce like for
                atrial fibrillation)
    -   Rivaroxaban (Xarelto): 15 mg BID x 21 days
        à
        20 mg daily
        -   Needs to be taken with food, avoid with CrCl\<30
    -   Dabigatran (Pradaxa): 150 mg BID **AFTER** 5 days of parental
        therapy
    -   Warfarin (Coumadin): Goal INR 2-3, requires frequent monitoring
        -   Need to be bridged with enoxaparin or heparin gtt
-   Duration of Anticoagulation:
    -   Major reversible/transient risk factors (surgery, trauma): 3-6
        months
    -   Idiopathic, unprovoked, or with less compelling risk factors: 12
        months
    -   Major permanent risk factors (cancer, homozygote F5L or
        prothrombin gene mutation, APLS, protein C/S deficiencies, AT
        III deficiency): At least 1 year, preferably lifelong.
    -   Recurrent DVT/PE: lifelong
