# Brief Overview of ART
 
Overview of Antiretroviral Therapy – Joseph Quintana

| 0                               | 1                                                                | 2                                          | 3                                                                                                                                                                                                    |
|---------------------------------|------------------------------------------------------------------|--------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Fixed Dose Combination regimens | Fixed Dose Combination regimens                                  | Renal Dose Adj.                            | Specific Considerations                                                                                                                                                                              |
| Biktarvy®                       | Bictegravir/ Emtricitabine/ Tenofovir (Alafenamide)              | d/c if CrCl \< 30; ok w/HD                 | ↑ Metformin levels Contraindicated w/: rifampin, dofetilide, rifabutin Avoid close admin. w/: laxatives, sucralfate, iron, calcium                                                                   |
| Triumeq®                        | Abacavir/ Dolutegravir/ Lamivudine                               | Dose adj individual components \<50 mg/min | Dolutegravir can ↑ metformin & dofetilide levels; dose adj needed w/rifampin use Same absorption issues with polyvalent cation administration (as below with bictegravir) also apply to dolutegravir |
| Genvoya®                        | Elvitegravir/ Cobicistat/ Emtricitabine/ Tenofovir (Alafenamide) | d/c if CrCl \< 30; ok in HD                | Many DDI with Genvoya (and other regimens with pharmacologic booster \[cobicistat\] due to CYP 3A4 inhibition                                                                                        |

| 0                           | 1                   | 2                                                                | 3                  | 4                                                                   |
|-----------------------------|---------------------|------------------------------------------------------------------|--------------------|---------------------------------------------------------------------|
| Nuceloside RTI              | Dose adj            | Specific SE                                                      | Major DDI          | Special Points                                                      |
| Abacavir (ABC)              | Hepatic dysfunction | ↑ LDL/TG ↑ risk MI                                               | Tenofovir (df)     | Requires testing for HLA B5701; Avoid if previous hyper-sensitivity |
| Emtricitabine (FTC)         | Renal (adj by CrCl) | Rash, Insomnia, Rhabdomyolysis, Hyperpigmentation in palms/soles | Lamivudine         | Active against HBV                                                  |
| Lamivudine (3TC)            | Renal (adj by CrCl) | Nausea, HA, peripheral neuropathy, neutropenia, rash             | Emtritabine        | Active against HBV                                                  |
| Tenofovir Alafenamide (TAF) | D/c for CrCl \< 15  | ↑ lipids in TAF vs TDF                                           | AED’s may $ levels | Tx of choice for HBV; ↑ lipids                                      |
| Tenofovir Disoproxil (TDF)  | Renal (adj by CrCl) | N/V, # LFT, asymptomatic # CK                                    | --                 | Active against HBV                                                  |

NRTI Additional Information

-   -   -   -   -   

-   Tenofovir
    alone is indicated for HBV, in which case you should be mindful of
    renal clearance when dosing. In HIV, it is only indicated in
    combination with emtricitabine and fixed-dose combination
    formulations, in which it is contraindicated if CrCl\<30

-   Class-wide Side Effect: Lactic acidosis, steatosis and lipoatrophy

-   Resistance: M184V confers high resistance to emtricitabine and
    lamivudine, mid-level resistance to abacavir

| 0                   | 1                      | 2                         | 3                                   | 4                                                                                           |
|---------------------|------------------------|---------------------------|-------------------------------------|---------------------------------------------------------------------------------------------|
| Integrase Inhibitor | Dose Adj.              | Specific SE               | Major DDI                           | Special Points                                                                              |
| Raltegravir (RAL)   | --                     | --                        | Rifampin, AED’s                     | --                                                                                          |
| Dolutegravir (DTG)  | \*see special points\* | Hyperglycemia Weight gain | Rifampin, Efavirenz ↑metformin lvls | Avoid close admin w/ laxatives, sucralfate,  iron, calcium May ↑Cr, w/o effect on renal fxn |

| 0                 | 1                     | 2                                                                | 3                                                                         | 4                                                                                            |
|-------------------|-----------------------|------------------------------------------------------------------|---------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|
| NNRTIs            | Hepatic Adj           | Specific SE                                                      | Major DDI                                                                 | Special Points                                                                               |
| Efavirenz         | D/c if Child Pugh B/C | Psychosis, vivid dreams, SI, mania, seizures; ↑ Lipids & glucose | Plavix, Azole, antifungals, some statins \* clarithromycin, Buprenorphine | Give before meals; d/c if rash develops                                                      |
| Etravirine (ETR)  | NaN                   | Hypersensitivity  ↑ Lipids & glucose                             | Plavix, clarithromycin                                                    | NaN                                                                                          |
| Nevirapine (NVP)  | D/c if Child Pugh B/C | Steven Johnson Syndrome                                          | Azoles, OCP’s, statins, clarithro-mycin                                   | Don’t start if CD4 \>250 in women, CD4 \>400 in men; Don’t admin w/antacids                  |
| Rilpivirine (RPV) | NaN                   | Depression                                                       | AED’s, PPI’s, dexamethasone                                               | Must be taken w/ full meal; Don’t use if HIV RNA \>100k + CD4 \< 200; Don’t admin w/antacids |
| Doravirine        | NaN                   | Nightmares                                                       | NaN                                                                       | NaN                                                                                          |

NNRTI Additional Information

-   -   -   -   -   

-   Class-wide Side Effect: hepatitis, rashes

-   Resistance: K103N resistance to efavirenz and nevirapine

| 0                   | 1                    | 2                                                             | 3                                                                          | 4                |
|---------------------|----------------------|---------------------------------------------------------------|----------------------------------------------------------------------------|------------------|
| Protease inhibitors | Hepatic Dose adj     | Specific SE                                                   | Major DDI                                                                  | Special Points   |
| Atazanavir (ATV)    | Based on Childs Pugh | Jaundice, Kidney stones AV block, Pancreatitis Rhabdomyolysis | CYP3A4 Inhibitors PPI and H2 blockers                                      | Admin w/ meals   |
| Darunavir (DRV)     | NaN                  | Rashes Pancreatitis                                           | CYP3A4 Inhibitors Azoles can be used cautiously with drug level monitoring | Must d/c if rash |
| Lopinavir (LPV)     | NaN                  | AV block, QT changes Pancreatitis Hepatitis                   | CYP3A4 Inhibitors                                                          | Admin w/ meals   |

Protease Inhibitor Additional Information

-   -   -   -   -   

-   All protease inhibitors must be boosted:
    -   Ritonavir: can cause MSK pain, rhabdomyolysis, not expected at
        usual doses
    -   Cobicistat: may increase Cr without effect on renal function

-   Class-wide Side Effects: hepatitis, hypersensitivity reactions,
    #
    cholesterol/TG, hyperglycemia, GI upset, lipodystrophy
