# AIDS Defining Conditions
 
AIDS Defining Clinical Conditions – Rebecca Choudhury

AIDS is defined by HIV infection with concurrent absolute CD4 count
\<200, CD4 percentage \<14%, or one of the following conditions,
predominately opportunistic infections and HIV associated malignancies

Neurologic

/Ophthalmologic

-   -   -   -   -   

CNS

toxoplasmosis

-   Presentation: Variable, depending on disease burden/location, may
    include AMS, headache, seizure, ataxia, and focal neurologic
    deficits, +/- fever and flu-like symptoms
-   Evaluation: MRI w/Ring-enhancing lesions on brain imaging ( *Note* :
    can appear similar to CNS lymphoma), serum Toxoplasma IgG/IgM and
    (ideally) CSF Toxoplasma PCR. Brain biopsy may be indicated if
    diagnostic uncertainty.
-   Management: Pyrimethamine, sulfadiazine, and leucovorin is the
    preferred regimen, discuss dosing with pharmacy. Alternative
    regimens: clindamycin, Bactrim, atovaquone, and/or azithromycin.

<!-- -->

-   -   -   -   -   

Progressive multifocal leukoencephalopathy (PML)

-   Presentation: chronic (weeks to months), progressive neurologic
    dysfunction, particularly incoordination
    and other motor dysfunction, aphasia, sometimes cognitive impairment
    and personality changes
-   Evaluation:  MRI brain w/patchy areas of demyelination in the
    subcortical white matter; location is variable, but p
    arietal, occipital, and cerebellar involvement are common. JC virus
    PCR from CSF. Brain biopsy (uncommonly done)
-   Management: Initiation of ART may slow/stop progression. Fatal if
    HIV goes untreated.

<!-- -->

-   -   -   -   -   

HIV-related encephalopathy

-   Presentation: Similar to other progressive dementias, with short
    term memory loss followed by
    worsening global cognitive dysfunction, motor deficits, sometimes
    seizures in late stages
-   Evaluation: MRI w/diffuse cerebral atrophy and/or demyelinating
    lesions similar to PML. CSF w/elevated protein +/- lymphocytic
    pleocytosis, with no alternative cause. Send HIV RNA from the CSF,
    usually + in HIV encephalopathy

<!-- -->

-   -   -   -   -   

Cryptococcal meningitis

-   Presentation: Subacute to chronically worsening HA and fevers;
    meningismus and photophobia may be present but are often absent;
    rarely, focal neurologic deficits
-   Evaluation: LP to check opening pressure and can send serum and CSF
    Cryptococcus Ag. Brain imaging may be non-diagnostic
-   Treatment: Induction therapy with amphotericin and flucytosine x14
    days (at least), with repeat LP close to end of
    induction to confirm CSF inflammation is improving and fungal
    culture is negative.
    Maintenance therapy consists of high dose fluconazole for at least 8
    weeks. Pts may require serial LP to manage ICP
-   Delay ART for several weeks after start of treatment to avoid risk
    of IRIS.

<!-- -->

-   -   -   -   -   

CMV retinitis (with vision loss)

-   Presentation: Blurry vision, focal blind spots, visual field
    deficits, or scotomas and floaters. Typically begins unilateral,
    though often progresses to bilateral involvement.
-   Evaluation: Always consult ophtho if you suspect it! Hemorrhagic
    retinitis, “tomato soup and milk” appearance on dilated exam. May
    cause complete retinal detachment. Check CMV pcr serum (or vitreous)
-   Management:  PO valgancyclovir (+intravitreous ganciclovir or
    foscarnet in severe disease). If not on ART, must delay ART for at
    least 2 weeks after start of CMV retinitis treatment to prevent
    immune recovery uveitis

Pulmonary

-   -   -   -   -   

Pneumocystis jirovecii pneumonia (PJP)

-   Presentation: fever, shortness of breath, cough (usually
    non-productive), sometimes night sweats and weight loss. Hypoxia out
    of proportion to exam.
-   Evaluation: CT chest appearance usually bilateral and diffuse with
    GGOs and cystic lesions of varying size. Large cysts can rupture,
    causing pneumothorax.
    -   Induced sputum (or bronchoscopy sample) with cytology and GMS
        stain.
    -   Send serum LDH and 1,3-BD-glucan:  should be elevated, but are
        nonspecific.
-   Management: Bactrim is the preferred treatment; PO is preferable as
    Bactrim is 100% bioavailable. \*\*If patient is hypoxic, need to
    consider of adding steroids, can measure A-a gradient. Alternative
    regimens may include primaquine + clindamycin or IV (NOT inhaled)
    pentamidine.

<!-- -->

-   -   -   -   -   

Pulmonary tuberculosis

-   Presentation: With low CD4, can have upper lobe cavities but also
    atypical radiographic pattern, including a normal-appearing CXR.
    Have a high degree of suspicion in any patient with advanced HIV and
    respiratory complaints.
-   Evaluation: TB skin tests and IGRAs have a high false negative rate
    in advanced HIV. At VUMC, any pt with HIV and respiratory complaints
    must be placed on airborne until TB ruleout- 3 sputum mycobacterial
    cultures collected at least 8 hours apart. If concentrated smear is
    negative x3, TB is unlikely (though have to follow up final culture
    to be sure).
-   Management: RIPE therapy is the standard initial treatment, with
    adjustment if needed for drug resistance or contraindications

<!-- -->

-   -   -   -   -   

Herpes simplex tracheobronchitis and/or pneumonitis/pneumonia

-   Evaluation: bronchoscopy with positive HSV PCR from BAL +/- lung
    biopsy. (Usually associated with HSV-1)
-   Management:  agent and duration not well defined for
    bronchopulmonary disease; depending on severity of presentation,
    likely IV acyclovir to start followed by transition to PO antiviral
    once evidence of clinical improvement, for a total of 10-14 days.

<!-- -->

-   -   -   -   -   

Recurrent pneumonia NOS

Histoplasmosis, cryptococcosis, coccidiomycosis, and non-TB
mycobacterial infections (including MAC) limited to the pulmonary system
are not AIDs defining illnesses, though pts with advanced HIV and other
severely immunosuppressed states are at higher risk.

Gastrointestinal

-   -   -   -   -   

Esophageal candidiasis

-   Presentation: Dysphagia, odynophagia or both. Concurrent
    oropharyngeal candidiasis (“thrush’) is common but not universal.
-   Evaluation: Typically presumptive. Treatment is the test; start
    fluconazole and consider EGD if symptoms do not improve after
    several days (in which case candidiasis may be severe, or it might
    not be the cause)
-   Management: Fluconazole; nystatin is ineffective, especially in the
    severely immunocompromised

<!-- -->

-   -   -   -   -   

Herpes simplex esophagitis

-   Evaluation: EGD shows diffuse ulcerations throughout the esophagus;
    in severe disease ulcers may coalesce into dark patches, “black
    esophagus.” Esophageal biopsy is definitive, but can infer based on
    EGD appearance and serum studies.
-   Management: Similar to other mucocutaneous infections, consider IV
    acyclovir at first and transition to PO once clinically improved

<!-- -->

-   -   -   -   -   

CMV esophagitis/enteritis/colitis

-   Presentation: GI bleeding (colitis) or dysphagia and odynophagia
    (esophagitis)
-   Evaluation: serum CMV PCR, consult GI for consideration of
    EGD/colonoscopy
-   Management: (val)ganciclovir, foscarnet if ganciclovir resistance or
    contraindication

<!-- -->

-   -   -   -   -   

Chronic (>1 mo) intestinal isosporiasis

-   Evaluation: Stool ova/parasite can capture Iospora belli (new name
    Cystoisospora belli), may need serial analysis due to intermittent
    shedding. Oocysts may also be seen on duodenal biopsy.
-   Management: Bactrim; pyrimethamine + leucovorin if Bactrim is
    contraindicated
    -   

Chronic intestinal cryptosporidiosis

-   Presentation: Diarrhea; may infect respiratory tract, causing
    nonproductive cough
-   Evaluation: on GiPP or Cryptosporidium Ag
-   Management: Early initiation or optimization of ART; Monotherapy
    with nitazoxanide is preferred; raising CD4 count >100 is necessary
    to cure infection

<!-- -->

-   -   -   -   -   

Recurrent salmonella septicemia

-   Generally sensitive to fluoroquinolones, but if not clinically
    improving as expected you can request sensitivities from the
    microbiology lab.

Neoplastic

-   -   -   -   -   

Non-Hodgkin’s lymphoma - Burkitt’s, immunoblastic (subset of DLBCL), and
1º CNS

-   -   -   -   -   

Kaposi’s sarcoma

-   Presentation: Distinctive mucocutaneous lesions, usually raised,
    papular, violaceous or darkly colored, non-tender and non-pruritic.
    Can also involve the visceral organs (esp lungs and GI tract) and
    deep lymphatic system.
-   Evaluation: clinical, tissue biopsy for staging, HHV-8 serum PCR.
-   Management: Limited mucocutaneous disease may resolve with
    initiation/optimization of ART, but widespread or resistant disease
    may require additional local therapies (ex radiation) or systemic
    chemo
-   Bacillary angiomatosis (caused by Bartonella) may present similarly,
    but can be distinguished from KS on biopsy. It is neither a cancer
    nor an AIDS defining clinical condition, and is usually treated with
    doxycycline.

<!-- -->

-   -   -   -   -   

Cervical cancer

-   Presentation, diagnosis, and treatment are essentially the same as
    in HIV-negative patients, but incidence is higher and disease
    progression is often more rapid

Multisystem/Miscellaneous

-   -   -   -   -   

Extrapulmonary or disseminated Mycobacterial infection (TB and non-TB)

-   TB can go everywhere; some notable extrapulmonary sites include
    lymph nodes (e.g., scrofula), bones and joints (e.g., Pott’s disease
    of the spine), pleura and pericardium, GU tract, and CNS. Dx can
    come from tissue culture and sometimes MTB PCR for more rapid
    detection (needs ID approval).
-   TB-IRIS may be severe (esp with high infection burden) and hard to
    distinguish from TB treatment failure; can also be seen in
    adequately treated TB (provoked by the presence of dead bacteria)
    and undiagnosed latent TB.
-   Disseminated MAC is usually diagnosed with AFB blood culture (only 1
    positive needed). Think about it in patients with uncontrolled HIV
    and severe immunosuppression (esp CD4 \<50), with unintentional
    weight loss, chronic diarrhea and/or dyspnea, and evidence of GI
    malabsorption or with bone marrow suppression

<!-- -->

-   -   -   -   -   

Extrapulmonary or disseminated Histoplasmosis, Cryptococcocosis, and
Coccidiodomycosis

-   Can be difficult to distinguish based on clinical presentation and
    imaging alone. Diagnosed by culture and/or antigen testing depending
    on the organism and site of infection, and diagnosis may be
    supported by serologic studies.
-   Initial treatment of choice: liposomal amphotericin B in almost all
    cases

<!-- -->

-   -   -   -   -   

Chronic mucocutaneous HSV

-   Defined as mucocutaneous lesions present for >1 month, can be
    present at any site
