# Stroke
 
Background

-   Former, nonpreferred term: **cerebrovascular accident**
-   Sudden onset, focal (usually one-sided) neurologic deficits:
    weakness, sensory loss, vision loss, ataxia/unsteadiness, vertigo,
    double vision, facial droop, dysarthria, aphasia
-   Differential:
    -   stroke (ischemic or hemorrhagic)
    -   seizure or post-ictal paralysis
    -   headache phenomena
    -   cervical spinal cord lesions, though these more commonly cause
        bilateral symptoms

<!-- -->

-   Stroke-like symptoms can also develop as recrudescence – previous
    stroke or brain lesion symptoms worsening with systemic
    toxic/metabolic/infectious processes (or hypotension)

Evaluation

-   Critical
    decision-making information: last known normal (LKN), time symptoms
    first observed, anticoagulation status, why pt is admitted, recent
    surgeries, history of bleeding (severe GIB or ICH), recent
    medications, last platelet count, and baseline neuro exam
-   If symptoms developed with LKN within 24 hours -> stroke alert!
    -   VUMC: call 11111 and tell the operator stroke alert and current
        pt location
-   NAVA: call an RRT and stat page **835-5137** , include in the page
    **911** at the end of the call back number to signal it is a stroke
    alert
-   Stat head CTP (order CTH/CTA) for consideration of tPA or
    endovascular therapy
    -   If renal fx is abnormal, discuss with neurology
    -   Generally, go for CTA if the pt is a thrombectomy candidate
    -   MRI/MRA is an option but takes longer (MRAs are also better with
        Gadolinium)
    -   Neurology service should be leading this portion

Management

-   Blood pressure goals
    -   Ischemic stroke: in general SBP \<220
    -   Pts with intracranial atherosclerosis may require higher BP to
        maintain perfusion, which may necessitate discontinuing BP meds
    -   Hemorrhagic strokes (which will be obvious on CTH): SBP \< 140
        (BP management is key)
        -   These pts are managed in Neuro ICU
        -   Reverse coagulopathies and keep platelets >100,000
