# Preventative Medicine
 
Preventive Medicine/Screening: (USPSTF) – Toaa Abuelenen, Emily Camp

-   Recommend
    downloading the “CDC Vaccine Schedules” App on your phone to more
    easily filter by medical condition or look at contraindications
-   https://www.cdc.gov/vaccines/schedules/index.html

| 0                                      | 1                                                                                                                                                                                                                                                                                                                                              | 2                                      |
|----------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------|
| Preventative Measures for ALL patients | Preventative Measures for ALL patients                                                                                                                                                                                                                                                                                                         | Preventative Measures for ALL patients |
| Cholesterol                            | Men \>35 or 20-35 with CV risk Women \>45 or 20-45 with CV risk                                                                                                                                                                                                                                                                                | Grade A UpToDate: Grade 2C             |
| Colorectal cancer                      | All adults age 50-75 - FOBT annually - FIT annually  - FIT-DNA (Cologuard) q 1 or 3 years - Colonoscopy q 10 years - Flexible sigmoidoscopy q 5 years Screen earlier if: family hx of CRC or adenomatous polyps at age \< 60, a personal hx of IBD, a confirmed or suspected hereditary CRC syndrome, or a hx of abdominal or pelvic radiation | Grade A                                |
| Diabetes screening                     | Adults age 40-70 who are overweight or obese                                                                                                                                                                                                                                                                                                   | Grade B                                |
| Cardiovascular health                  | Blood pressure screening annually adults \>18                                                                                                                                                                                                                                                                                                  | Grade A                                |
| Cardiovascular health                  | Aspirin 81 mg in age 50-59 with ASCVD risk \>10% in 10 years, are not at increased risk for bleeding, have a life expectancy of at least 10 years, and are willing to take low-dose aspirin daily for at least 10 years.                                                                                                                       | Grade B                                |
| Cardiovascular health                  | Statin: See section on Lipids                                                                                                                                                                                                                                                                                                                  | Grade B                                |
| Hepatitis C                            | Adults aged 18 to 79 years (one time screening).                                                                                                                                                                                                                                                                                               | Grade B                                |
| HIV                                    | All adolescents and adults 15-65 (one time screening)                                                                                                                                                                                                                                                                                          | Grade A                                |
| Lung cancer                            | Low-dose CT adults 55-80 w/30 pack year smoking history and currently smoke or quit within the past 15 years Should discuss risk vs benefits, particularly in pts with serious co-morbidities who may not tolerate/desire surgery or aggressive treatment.                                                                                     | Grade B                                |
| Obesity                                | BMI annually in all adults                                                                                                                                                                                                                                                                                                                     | Grade A                                |
| Depression                             | All adults including pregnant and post-partum women                                                                                                                                                                                                                                                                                            | Grade B                                |

| 0                                | 1                                                                                                                                                                                                                                                                                                                                                                                                | 2                                |
|----------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------|
| Preventative Measures for WOMEN: | Preventative Measures for WOMEN:                                                                                                                                                                                                                                                                                                                                                                 | Preventative Measures for WOMEN: |
| Cervical cancer                  | Ages 21-29: q 3 yrs with cervical cytology alone. Ages 30-65: q 3 yrs with cervical cytology alone, every 5 years w/ high-risk human papillomavirus (hrHPV) testing alone or q 5 yrs with hrHPV testing in combination with cytology (co-testing) \*\*\*ACS 2020 guideline change –Age 25-65: preferred HPV test alone q 5 years (or HPV/Pap co-test every 5 years or a Pap every 3 years)\*\*\* | Grade A                          |
| Breast cancer                    | Women 50-74: q2 years ACS recommends beginning at age 40, Yearly If family or personal history of breast, ovarian, tubal, or peritoneal cancer or who have an ancestry associated BRCA1/2 gene mutations - should assess risk and refer to genetic counseling.                                                                                                                                   | Grade B                          |
| Chlamydia Gonorrhea              | All sexually active women \< 24, older women with increased risk                                                                                                                                                                                                                                                                                                                                 | Grade B                          |
| Osteoporosis (DEXA)              | Women \>65, postmenopausal women \<65 with increased osteoporosis risk (can use FRAX tool)                                                                                                                                                                                                                                                                                                       | Grade B                          |

| 0                                         | 1                                                                                                     | 2                           |
|-------------------------------------------|-------------------------------------------------------------------------------------------------------|-----------------------------|
| Preventive Measures for MEN               | Preventive Measures for MEN                                                                           | Preventive Measures for MEN |
| Abdominal aortic aneurysm (AAA) screening | Men Ages 65-75 who ever smoked (at least 100 cigarettes total): one-time screening by ultrasonography | Grade B                     |
