# Anesthesia
 
-   May be used in which a pt’s pain or anxiety may impede performance
    and success
-   Relative Contraindications: old age, dementia, respiratory
    difficulty
-   Aim to use local anesthesia and minimize procedural sedation
-   Local Anesthesia: lidocaine 1% or 2% – add Epi if >30 mins of
    analgesia required
-   Creating wheal: clean surface w/ chlorhexidine or alcohol swab; with
    22-25G needle, advance needle parallel to skin and aspirate to
    ensure no blood vessel involved, then inject anesthetic to create
    1-2 cm of raised skin; If deeper subcutaneous anesthesia is needed,
    advance needle perpendicular to skin, aspirate as advancing then
    inject the tract. Inject anesthetic as needle withdrawn.
-   Local anesthesia can alter landmarks, always double check anatomy
    after injection
-   Minimal Sedation: 0.25mg-2mg Ativan IV or 1mg-2.5mg Midazolam IV
-   Midazolam (Versed): faster on (2-5 min) and faster off (30-60 min)
-   Lorazepam (Ativan): onset 5-10 min; Duration 4-8 hours
