# Ultrasound-Guided Peripheral IV
 
Video Guide:

https://www.youtube.com/watch?v=GQGhciB6TvM

Relative Contraindications

-   Infection over the site, Hemodialysis in that arm (unless cleared by
    renal), Severe bleeding diathesis
-   We avoid EJs due to airway compromise if extravasation occurs

Pre-procedure considerations

-   Location selection: anuric AKI or ESRD patients – d/w renal
-   Target selection should follow the rule of 2s. Vein must be at least
    twice the diameter of the catheter being placed, should be no more
    than 2 inches in depth from the surface of the skin, and should have
    at least 2 inches of straight (non-tortuous) length

Procedure considerations

-   US Probe: Linear
-   Kit: IV start kit; ideally 18G needle
-   Anesthetic use: Consider EMLA
-   1 <sup>st</sup> choice: basilic vein; 2 <sup>nd</sup> choice:
    brachial vein
-   Use tourniquet; start at 45
    ° angle
-   Going too shallow could use up too much catheter leaving nothing to
    put in the vein.
-   Going too steep can cause catheter kinking at the hub where it
    sticks out of the skin
-   Hold probe close to skin, holding probe far from the end allows too
    much movement
-   Center the vessel on the ultrasound probe screen prior to sticking
-   Use both short axis and long axis views to ensure correct placement
-   Short axis- Vessel looks round like a target, helps to scout out the
    tip, and is best for ensuring the vein is entered as opposed to a
    neighboring artery
-   Long axis- The length of the vessel is viewed. This view is intended
    for the final few millimeters of catheter advancement into the vein
    to ensure both bevel and plastic sheath lumen traverse the
    endothelial layer before threading catheter

Post-procedure considerations

-   DON’T FORGET TO REMOVE TOURNIQUET!! Remove before flushing to
    prevent blowing vein
-   Bleeding complication: if arterial, remove catheter & hold pressure
    at least 5 mins
