# Consent
 
-   When printing Consents at VUMC, use MedEx (on the virtual
    machine/desktop)
-   Ensure pt’s signature; Telephone consent requires second physician
    as witness
-   Use CSN (not the MRN) to locate the pt information for that specific
    admission or office visit – ensure patient current room number on
    MedEx screen
-   When consenting pts at NAVA, use the COW with pen pad and the
    I-Consent program
-   Video guide:
    https://www.youtube.com/watch?v=6yXOEkFqk2o

Lumbar Puncture

-   Common risks: backache (\~66%), severe headache
-   Rare risks: spinal hematoma (\<0.001%), weakness, numbness, brain
    function problems, CNS infection, brain herniation

Paracentesis

-   Risks: abdominal wall hematoma (1%), hemoperitoneum, organ puncture,
    infection

Thoracentesis

-   Common risks (> 5%): coughing, fainting, PTX
-   Rare risks (\< 1%): hemothorax, emergency surgery, re-expansion
    pulmonary edema

Arthrocentesis

-   Common risks: pain during procedure, repeat needle insertion
-   Rare: damage to surrounding vessels, nerves; iatrogenic septic
    arthritis: (\<0.1%)

Dobhoff Tube Placement

-   Common risks: Malpositioned (lung)/coiled tube; perforation anywhere
    along the tract; cranial placement; aspiration, gastritis, bleeding,
    vagal response, significant discomfort
-   Contraindications: SBO, ileus; use large bore NGT instead (placed by
    bedside nurse)

US-Guided PIV Placement

-   Common risks: arterial puncture, nerve irritation/damage
    during/after procedure, infection, infiltration, thrombus formation
