# Substance Use Disorder
 
Substance Use Disorder (SUD)– Barrington Hwang, Kristopher Kast

Background

-   SUDs are common, complex, and chronic neuropsychiatric
    disorders
    with well-described inherited risk, dysregulated neurophysiology,
    and multiple effective treatment modalities
-   Pts w/SUD
    face significant stigma, prior traumatic experiences in healthcare
    environments
-   Approaching pts respectfully and fostering partnership is important
    to quality care
-   Using
    the term “abuse” undermines the disease model of addiction,
    connoting volitional “bad” behavior driving recurrent substance use
-   Person
    -centered, specific terminology: “person with opioid and alcohol use
    disorders”
-   Avoid the qualifier “Polysubstance,” suggests the specific diagnoses
    are less important data
-   Clarify specific diagnoses for each substance category:
    -   Identify
        the
        current substance exposures and distinguish use
        disorder
        from unhealthy use and episodic use
-   DSM 5 Criteria (same for most substance categories): Requires 2+
    criteria met in past year; use must cause clinically significant
    impairment and/or distress:
    -   Loss of control – larger amounts, longer time, ongoing use
        despite consequences, efforts/desire to reduce use
    -   Physiologic changes -- tolerance, withdrawal (these 2 alone do
        not necessarily imply a disorder if they result from prescribed
        therapy), craving
    -   Consequences – hazardous use, interpersonal problems, medical
        problems, failed role obligations, lost activities
-   In the general hospital, SUD management first requires identifying
    and stabilizing withdrawal states to mitigate risks of severe
    sequelae (seizure, delirium), unintended iatrogenic harm (opioid
    abstinence leading to lost tolerance and post-discharge overdose),
    and distress-driven AMA discharge

General Management:

-   Consider Addiction Psychiatry consultation for management of complex
    withdrawal states, substance use disorders and co-occurring
    psychiatric diagnoses, assistance with risk stratification for
    hospital misuse and/or hospital discharge with PICC lines for
    outpatient antibiotics, and differentiation of pain requiring opioid
    therapy and opioid use disorder
    -   At VUMC: In Epic, “Inpatient Consult to Psychiatry, Addiction
        Medicine”
    -   Team consists of addiction psychiatrists, nurse practitioners,
        fellows/residents, social workers, and recovery coaches
-   If in the emergency room and not admitted, consult PAS

Opioid

Use Disorder – Rita Hurd, David Marcovitz

Background

-   Standard
    of care is opioid stabilization with buprenorphine or methadone (in
    OUD) or other full agonist opioids (in chronic opioid therapy)
-   Methadone
    and buprenorphine can be ordered by any physician for inpatients
-   Maintenance
    agonist therapy should be offered to every patient, with preference
    for an “opt-out” approach (even for uninsured patients through state
    grant funding)

Presentation (Withdrawal)

-   Restlessness
    /psychomotor activation, anxiety, irritability, nausea, abdominal
    cramping, loose stool, diffuse musculoskeletal pain, chills,
    Insomnia, yawning
-   Pupillary
    dilation, piloerection, tearing, nasal congestion, diaphoresis,
    restless legs

Evaluation

-   Clinical
    Opioid Withdrawal Scale (COWS): quantifies severity of opioid
    withdrawal and allows for safer buprenorphine inductions
-   Asking
    about opioid exposure: “You’re uncomfortable. I work with a lot of
    people in the hospital, and some come with regular exposure to
    opioids from a lot of different places (their doctors, friends),
    should we be treating any withdrawal for you?”

Medications for Opioid Use Disorder (MOUD)

Buprenorphine

-   Partial
    agonist at the mu opioid receptor with high binding affinity
-   Long
    half-life (24-36 hours) allows for daily dosing
-   TID
    dosing is more effective for **acute pain** (as the analgesic effect
    is shorter-lived)
-   OK
    to use in renal failure/HD; may reduce dose in hepatic injury
-   All non-pregnant pts should receive buprenorphine-naloxone (e.g.
    Suboxone)
    formulations
    to mitigate risk of diversion/injection
-   Induction
    :
    -   Hold all opioid medication 12+ hours prior to first
        buprenorphine dose (typically, this opioid-free period is
        overnight from 9 PM to 9 AM), with a recorded COWS score >8-10;
    -   4 mg is given SL, monitoring for oversedation; additional 4 mg
        is given in 1 hour, and final 4 mg at 4 hours (total of 12 mg in
        first day)
        -   Only sedation or hypopnea should prevent a full 12 mg dose
    -   Typical
        starting
        dose: 12-16 mg/day
-   Maintenance
    :
    4-32 mg daily; 16mg and above to suppress opioid use
    -   Requires waivered-provider
-   Acute
    Pain Management in pts using Buprenorphine:
    -   There is no contraindication to full-agonist opioid analgesia
        for breakthrough pain
        -   If the etiology of pts pain would require opioid therapy in
            a non-OUD patient, do not avoid opioids; these may be used
            safely in the hospital
    -   Peri-operative pain management: continue buprenorphine at
        reduced and split doses (4 mg BID or TID); will prevent
        withdrawal and cravings, but NOT manage new pain
    -   Post-operatively: reduce opioid requirements and increase
        buprenorphine to home dose
        -   If buprenorphine was discontinued, will require induction
            procedure

Methadone

-   Full mu opioid agonist with additional NMDA-receptor activity
-   FDA-approved for OUD when dispensed from a licensed opioid treatment
    program
-   Better option for individuals who cannot tolerate the buprenorphine
    induction procedure, with significant chronic or escalating pain
    -   Long t <sup>1/</sup> <sub>2</sub> : 12-36 hrs; max 10 mg/d q7d,
        to prevent dose-stacking and delayed overdose
-   Safe in renal failure; dose reduction for hepatic injury
-   Potential for QT prolongation at higher doses, warrants QTc
    monitoring
-   Induction
    :
    -   In the hospital, start at 10 mg TID, holding doses for sedation
        or hypopnea; lower doses if concerned for respiratory compromise
        or concurrent CNS depressant therapy
    -   Limit 40 mg in first 24 hours; then titrate 5 mg/d q3d while
        admitted
-   Maintenance
    :
    -   Must confirm dose with methadone clinic before restarting
        outpatient dose; until then, do not give more than initial doses
        (30 mg in single dose, 40 mg in first 24 hours)
    -   After confirming home dose, continue as single daily dose

Naltrexone

-   Mu opioid antagonist; Half-life oral \~4 hours but clinically active
    \~24 hrs
-   IM maintains clinically effective levels up to 30 days
-   High affinity for mu receptor --> CAN precipitate withdrawal
    requiring 7-10 days opioid abstinence prior to initiation
-   If due for monthly injection while admitted, may substitute oral
    formulation until discharged to outpatient provider to receive
    injection

Additional Information

-   Psychosocial Interventions that complement MOUD:
    -   Consider referral to SUD counseling, mutual help (self-help,
        12-step, AA), intensive outpatient, and short- or long-term
        residential treatment
    -   Use of other drugs NOT a contraindication to MOUD, however
        should encourage abstinence from other drugs during therapy
        (especially benzodiazepines)
-   Prescribe intranasal naloxone for overdose prevention to all OUD
    patients discharging from hospital, regardless of MOUD status

Alcohol Use Disorder – Barrington Hwang , Kristopher Kast

Background

-   50% of hospitalized pts drink alcohol; at-risk alcohol use is >14
    drinks/week or >5 drinks in a sitting (for men; for women and
    men >65, 7 per week, >4 per sitting)
-   Alcohol
    withdrawal onset occurs 6-12 hours after last drink, with 90% having
    non-severe course; CIWA score \<10 at 24-48 hours indicates low risk
    of worsening symptoms
-   Risk
    of seizures greatest at 12-24 hrs, occurring in \~3% of pts; risk of
    delirium greatest at 48-72 hrs, occurring in \~5%
-   Risk
    assessment
    -   RF: prior seizures/delirium, co-substance use (especially
        benzodiazepines), no abstinent days in past month, presenting
        BAL >200, dysautonomia
    -   CIWA symptom-triggered protocol appropriate for pts at **low**
        **risk** of severe withdrawal
    -   For non-low risk pts, consider benzodiazepine/barbiturate load
        and standing taper;
-   Indications
    for
    admission: prior severe withdrawal (withdrawal seizures or
    delirium), comorbidities (medical and psychiatric illness),
    pregnancy, significant impairment in social/occupational
    functioning, communication barriers, social barriers

Presentation

-   Acute
    intoxication: disinhibition, slurred speech, ataxia, nystagmus
-   Acute
    Withdrawal:  nausea, vomiting, anxiety, agitation, audio-visual and
    tacticle
    hallucinations
    , headache, diaphoresis, fine motor tremor while arms and fingers
    outstretched, autonomic hyperactivity
-   Chronic
    heavy use:
    -   Sequelae of chronic liver disease & malnutrition, including
        thiamine deficiency
-   Caine
    criteria for Wernicke’s encephalopathy:
    -   2 or more: (1) malnutrition, (2) ataxia, (3) oculomotor
        abnormalities, (4) AMS

Evaluation

-   Identify
    last use, quantity per day/week, other sedative-hypnotic use,
    history of withdrawal, social/occupational dysfunction, other toxic
    forms of alcohol compounds including methanol, ethylene glycol
-   Acute
    Alcohol
    Withdrawal
    -   Labs: Blood alcohol level, urine toxicology (+/- ethyl
        glucuronide to detect use in prior 3 days), BMP, CBC, HFTs
        (AST:ALT elevation 2:1), CK and
        β
        \- hCG

<!-- -->

-   CIWA
    score quantifies severity, though subject to inflation by subjective
    symptoms
-   Objective Alcohol Withdrawal Scale (OAWS) is an alternative for pts
    at risk of over-reporting symptoms

Management

Acute Alcohol Withdrawal

-   Most patients are appropriate for diazepam-based protocols:
    -   CIWA-based symptom-triggered for low-risk patients
    -   Diazepam load + standing taper for non-low risk patients
-   Substitute lorazepam for pts with hepatic impairment (risk of long
    acting accumulation)
-   Benzodiazepine resistance: likely due to poor cross-tolerance, these
    pts  require phenobarbital load ( 8-12 mg/kg (up to 15 mg/kg)
    divided into 3 doses 3 hours apart)
-   Add folate, multivitamin, and electrolyte repletion
-   If >2 Caine criteria, treat empirically for Wernicke’s
    encephalopathy with high-dose IV thiamine (500 mg TID IV x 3-5 days)

-      Consider Addiction Psychiatry consultation for complex
presentations

Alcohol Use Disorder

-   After withdrawal stabilization, engage pt in discussion around use
    and educate on connection between use and presenting medical
    problems
-   All patients with AUD should be initiated on pharmacotherapy (MAUD)
    prior to discharge to mitigate risk of relapse, if consistent with
    patient’s goals
-   Additional psychosocial treatments effective for AUD include
    motivational interviewing, 12-step groups (AA, SMART Recovery),
    cognitive behavioral therapy, sober living facilities, family
    therapy, contingency management, and IOP/residential facilities
-   If patient does not have abstinence goal, reduced or controlled
    drinking may allow for harm reduction; naltrexone and topiramate
    have evidence for non-abstinence outcomes

<!-- -->

-   Pharmacologic
    Interventions:
    -   Naltrexone
        (cannot be on opioid agonist):
        -   Need 7-10 days since last opioid before starting
        -   25 mg x1 day, then titrate up to 50 mg daily; also available
            in q30d IM
        -   Monitor liver enzymes; AST/ALT must be \< 3-5x ULN
    -   Acamprosate
        (cannot be used in severe renal impairment)
        -   Head-to-head, inferior to naltrexone (see COMBINE trial)
        -   333 mg TID, titrating to 666 mg TID dosing
        -   Difficult TID dosing may be helpful if framed as
            commitment/mindfulness practice
    -   Disulfiram
        -   Infrequently used outside of extreme motivation (e.g.
            professional under monitoring); would not use outside
            specialist care
        -   Must abstain from alcohol \~2 weeks after last dose, given
            risk of disulfiram-ethanol reaction (DER), which can be
            fatal depending upon disulfiram and ethanol doses
    -   Topiramate
        -   Not FDA-approved for AUD, but has significant supporting
            evidence
        -   Useful for individuals without abstinence goal
        -   Titrate slowly over 8 weeks to 200-300 mg/d
    -   Gabapentin
        :
        -   Not FDA-approved for AUD, but with some evidence
        -   Useful for post-acute withdrawal anxiety, insomnia, or
            co-occurring neuropathy
        -   Titrate to 900-1800 mg/d divided into TID dosing, monitoring
            for sedation
        -   Risk
            of sedation/apnea if concomitant alcohol use; ensure pt
            educated about risk
