# Inpatient Insomnia
 
Inpatient Insomnia – Julian Raffoul, Jose Alberto Arriola Vigo

Background

-   Sleep disturbances in the hospital are multifactorial
-   Consequences of sleep disturbances in the hospital include changes
    in cognition, behavior, anxiety, pain perception, respiratory
    function, inflammation, and metabolism
-   Goals while inpatient: optimize sleep environment, minimize
    stimulating or sleep-related side effects of concomitant
    medications, utilizing non-pharmacologic strategies

Management

-   Non-pharmacologic interventions:
    -   Noise reduction:
        use of ear protection, sound masking (white noise), sound
        proofing acoustic materials, and behavioral modifications (or
        "quiet time" protocols)
    -   Light therapy
        : Use of eye masks in conjunction with ear plugs will improve
        sleep, however, nocturnal light appears to be less of an issue
        compared with inadequate daytime light exposure, which improves
        circadian rhythms, nocturnal sleep, and minimizes delirium
        -   Light exposure typically consists of two to five hours of
            daytime to early evening light in the range of 2000 to 5000
            lux
    -   Reducing nighttime interruptions:
        Alter workflow/lab draws, if possible, to permit 8-hr nocturnal
        "quiet time"
    -   Relaxation techniques:
        Music or white noise may
        ↑
        subjective sleep quality and duration
    -   Equipment:
        for severely ill pts, minimize hardware and tubes that can alter
        sleep due to physical presence and alarms
-   Pharmacotherapy:
    -   Melatonin:
        1-5 mg PO qhs; (dosing is not standardized); the best first-line
        choice based on mild side-effect profile, low potential for
        drug-drug interactions, and improves circadian rhythms; Most
        effective 2-3hrs before bedtime
    -   Ramelteon:
        8 mg PO qhs; a melatonin-receptor agonist; May also play a role
        in preventing delirium in older adult inpatients
    -   Trazodone:
        25-50 mg PO qhs (max 200 mg/day); a serotonin modulator w/
        significant sedation as a side effect, also headache, dry mouth,
        and nausea are common
        -   Monitor for orthostasis and infrequent atrial arrhythmias;
            use lowest effective dose
    -   Mirtazapine:
        7.5-15 mg PO qHS; a primary alpha-2 antagonist with 5-HT2 and H1
        antagonism, consider when insomnia appears to be related to
        primary depression
        -   Advise that appetite and weight gain may also occur
    -   Minimize
        medications such as vasopressors, sedatives/hypnotics, opioids,
        glucocorticoids, beta blockers, and certain antibiotics that
        disturb sleep architecture

Additional Information

-   Avoid the following in the inpatient setting:
    -   Benzodiazepines
        :  While effective at reducing sleep latency and increasing
        total sleep time, benzodiazepines are associated with
        significant adverse effects, particularly in older adults, e.g.,
        respiratory depression, cognitive decline, delirium, daytime
        sleepiness, and falls, particularly in hospitalized adults
    -   Non
        \-
        benzodiazepines
        : Benzodiazepine receptor agonists (e.g., zolpidem,
        eszopiclone/zopiclone, zaleplon) are effective in the outpatient
        setting and commonly used in the inpatient setting; however,
        they may be associated with cognitive dysfunction, delirium, and
        falls in hospitalized patients
    -   Diphenhydramine
        : Trials evaluating their effectiveness as sleep aids are
        limited and show mixed results w/ many potential side effects
        that are enhanced in the inpatient setting: *impaired cognition*
        , *anticholinergic effects* (constipation, urinary retention)
    -   Others
        : ( **anticonvulsants** , **antidepressants** ,
        **antipsychotics** , **barbiturates** ) are usually used in
        outpatient setting, but have not been well studied in the
        inpatient setting
