# Hypoxia
 
| 0                     |
|-----------------------|
| Hypoxia – Henry Brems |

Background

-   Two major ways to measure oxygenation, which are similar but
    distinct:
    -   SpO2 or "pulse ox" - most common measurement in the hospital or
        clinic, which measures the O2 saturation of Hgb at capillary
        level
        -   \<95% is abnormal, but may not need supplemental O2 until
            \<90-92% in most pts
    -   PaO2 -- the partial pressure of oxygenation measured on an ABG
        -   \<80 mmHg is abnormal
-   The relationship between SpO2 and PaO2 is the classic S-shaped
    curve.
-   Below an SpO2 of \~88%, PaO2 begins to fall off dangerously fast
    thus necessitating quick intervention for pts with SpO2 below this
    level

  

Mechanisms of Hypoxia:

| 0                             | 1                                                                                                                                                                                                    |
|-------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Mechanism                     | Pathophysiology                                                                                                                                                                                      |
| Decreased barometric pressure | \- Normal A-a gradient - This is unlikely to be seen except at high altitudes                                                                                                                        |
| Hypoventilation               | \- Normal A-a gradient - Hypoxia easily correctable with supplemental O2                                                                                                                             |
| V/Q Mismatch                  | \- Increased A-a gradient - Processes that lead to areas of lung where V/Q \<1, i.e. where there is relatively less ventilation than perfusion. - Common examples include PNA, ARDS, pulmonary edema |
| Right-to-left Shunt           | \- Increased A-a gradient - Can be anatomic (e.g intracardiac, AVMs) or physiologic (water/pus/blood filling alveoli) - Classically does not easily correct with supplemental O2                     |
| Diffusion Limitation          | \- Increased A-a gradient - Often related to diseases affecting interstitium -- e.g., ILD                                                                                                            |

Differential diagnosis for hypoxia based on anatomical location:

| 0                            | 1                                                                                                                                                                                                         |
|------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Anatomical Location          | Differential Diagnosis                                                                                                                                                                                    |
| Airways                      | \- COPD most common, Asthma in very severe cases - CF, bronchiectasis in patients with appropriate history                                                                                                |
| Alveoli                      | \- Any process that fills the alveoli with: Blood Pus -- infection from bacterial, viral, fungal agents Water -- pulmonary edema Protein/Cells/Other -- ARDS, pneumonitis (e.g. aspiration, drug-induced) |
| Interstitium/Parenchyma      | \- Interstitial Lung Diseases (see section)                                                                                                                                                               |
| Vascular                     | \- Pulmonary Emboli - particularly suspect these in patients with significant hypoxia and a clear CXR                                                                                                     |
| Pleural Space and Chest Wall | \- Pleural Effusions, Pneumothorax, Neuromuscular weakness, tense ascites - These are more likely to cause significant dyspnea and usually need to be quite severe to cause hypoxia                       |

Evaluation

-   Confirm true hypoxia with good pleth. Can press pulse-ox on pt’s
    finger for better transmission
-   CXR is almost always the first step
-   Other common initial workup: CBC, BMP, BNP, troponin, EKG, ABG/VBG
-   TTE -- particularly useful if suspected new pulmonary edema or
    pulmonary HTN
    -   Obtain with 'bubble study' if any concern for shunt
    -   Obtain “limited” if patient had recent “complete” TTE
-   Chest CT
    -   Order CTA ('CTA PE' in Epic) if concerned for PE
        -   V/Q scan if unable to receive IV contrast
    -   CT Chest without contrast otherwise generally preferred for
        evaluation of lung parenchyma
-   PFTs are useful if there is suspected obstructive (e.g. COPD) or
    restrictive disease (e.g. ILD), or if the cause remains otherwise
    unknown after initial workup
    -   These are almost always done as an outpatient

Management

-   Should be directed at underlying cause. See other sections for
    information relevant to particular diagnoses
-   If acutely decompensating, Duonebs, IV lasix, Antibiotics depending
    on clinical picture
-   Supplemental O2 for goal SpO2:
    -   \>90-92% for most patients (There is generally no need to make
        SpO2 100%)
    -   Between 88-92% for patients with chronic hypoxia from COPD
        (i.e., on home O2)
