# Diabetes: Inpatient Management
 
Inpatient Diabetes Mellitus (DM) – Will Bassett

Blood glucose (BG) goal:

-   Wards
    : \<140 mg/dL fasting; \<180 mg/dL random; increase for elderly,
    “sicker” patients
-   ICU
    : 140-180 mg/dL (NICE-SUGAR Trial)
-   Avoiding moderate-severe hypoglycemia in ill patients is more
    important than ideal BG

History: Year of dx, prior DM meds, current meds, last A1c (date and
value), home BG readings, history of hypoglycemia, # of hospitalizations
for diabetes, history of DKA, history of nephropathy, neuropathy,
retinopathy or foot disease.

Initial orders:

-   HOLD
    all home oral diabetes meds
-   Dose reduce home insulin (typically to 50-60% of home dose) for
    changes in diet and renal function. For AKI consider reducing by
    more
    -   Do NOT hold basal for T1DM- would not reduce \<80% of home dose
        in most cases
-   Sliding Scale Insulin (Order set “SUBCUTANEOUS INSULIN ORDER(S)”)
    -   Hemoglobin A1c: can consider if none in last 3 months and
        concern for poor outpatient control. Does not routinely affect
        inpatient management
    -   Fingerstick blood glucose: Typically AC/HS (before meals and
        nightly)
    -   Hypoglycemia management: Select all of these
    -   Basal insulin:
        -   T **ype 2 DM** , consider
            ↓
            home dose (50-60% to home dose) as often inpatients have
            reduced PO intake and
            ↓
            renal function
        -   Type 1 DM
            , DO NOT hold basal insulin, and avoid
            ↓
            \< 80% of home dose
        -   Unnecessary if no home basal insulin
    -   Insulin lispro meal:
        ↓
        home dose by 1/2, can also d/c, do not give while NPO
    -   Lispro insulin correction scale: Start with Low or Medium
        sliding scale and
        ↑
        prn
-   Carb-controlled or carb-restricted diet

Adjustments:

-   In
    EPIC, go to Summary tab and search “glucose” for BG trends and
    insulin dosing (Easiest to follow this tab if you ask for All
    results and expand the view fully on the right)
-   If BGs persistently >200
    -   Calculate all insulin needs over 24h (basal + mealtime + sliding
        scale)
        -   Give 50% as basal Lantus and other 50% as mealtime doses
        -   Ex: 10 basal + 0 mealtime + 14 sliding scale total = 12
            Lantus + 4 w/ each meal
        -   If new to basal, safe start is Lantus 0.2 un/kg daily if
            normal GFR (lowest dose 10 un for T2DM, only brittle T1DM
            may need lower)
    -   Can also address mealtime and nightly glucose separately
        -   If AM glucoses are high, but prandials well controlled,
            consider increasing basal
        -   If controlled in AM but elevated with meals, consider
            increasing mealtime
-   If BGs \< 70
    -   If overnight/AM, reduce basal
    -   If daytime, reduce mealtime and sliding scale
    -   Less is more! Blood glucose in the 200s is better than the 50s
    -   If endocrine consulted (“Glucose management services) for inpt
        glucose mgmt, please notify >24h prior to d/c if you want
        recommended d/c regimen!  

Steroid-induced Hyperglycemia:

-   -   -   -   Steroids increase insulin resistance
                →
                elevated postprandial BG most notable
            -   2-3 fold
                ↑
                in TDD insulin usually required w/ high dose
                (prednisone > 20 mg)
            -   Common approaches:

    -   Double prandial + correction dose (basal the same)

    -   Modified basal bolus regimen (30% basal, 70% bolus)

    -   Add NPH (weight + dose based, per below\*)— If on prednisone
        once daily (and not already on MDI), can add NPH once daily
        (give at same time as prednisone d/t similar pharmacologic
        profile if terms of peak effect and duration)
        -   prednisone 10 mg = 0.1 u/kg NPH
        -   prednisone 20 mg = 0.2 u/kg NPH up to max dose NPH 0.4 un/kg
            daily (w/ prednisone)
        -   \*lower dose
            if AKI

Additional Information

-   VA tips:  At the VA, NPH is formulary rather than Lantus. If a pt
    takes Lantus at home, this can be continued, but otherwise you will
    need to place a PADR consult. NPH’s duration of action is shorter
    than Lantus (12-18 hrs if normal GFR) and in most cases should be
    dosed Q12h. The conversion is done by taking total Lantus dose and
    dividing it two doses.
-   Ex: home Lantus 20 units qhs
    →
    NPH 10 units BID
-   Patients
    getting tube feeds:
    -   Best with continuous tube feeds to give regular insulin q6h (not
        TIDAC since they don’t have  distinct “meals”); you can titrate
        rapidly, turn off safely (e.g procedures)
    -   Then consolidate for bolus feedings based on 24-hour insulin
        needs prior to d/c
-   Patients with insulin pumps
    :
    -   If a patient has a pump and supplies, reasonably controlled BG,
        is willing and able to manage pump then s/he can keep the pump
        on
    -   Still order POC BG checks ACHS for nurse to chart and fill out
        MedEx pump contract
    -   Consult Endocrine routinely
