# NASH and NAFLD
 
| 0                                |
|----------------------------------|
| NASH and NAFLD – John Laurenzano |

Background

-   Non-alcoholic fatty liver disease (NAFLD): presence of hepatic
    steatosis in the absence of secondary causes (e.g., EtOH)
-   Non-alcoholic steatohepatitis (NASH): evidence of active
    inflammation in conjunction with steatosis (elevated liver enzymes
    or evidence on bx)
-   Strong association with metabolic syndrome, T2DM, HTN, obesity,
    prior cholecystectomy
-   Generally asymptomatic
-   Considered to be a common cause of cryptogenic cirrhosis

Evaluation

-   -   -   

-   NASH manifests with elevated liver enzymes, typically 2-5x the ULN,
    in a roughly 1:1 ratio (as opposed to alcoholic steatohepatitis),
    though ALT may be higher than AST

-   NAFLD is asymptomatic and frequently found incidentally via imaging

-   Can be diagnosed based on imaging alone (and frequently is)

-   Exclusion of alternative causes and comorbid liver conditions: HCV,
    HBV, EtOH

-   Liver biopsy

-   Generally only pursued with advanced disease and to evaluate extent
    of fibrosis, or to rule out competing etiologies, such as AIH

-   Note: Ferritin is frequently elevated, though not to the extent of
    HH. Low level auto-antibodies are also frequently present

-   Ultrasound is used most frequently for imaging, though MRI and CT
    also are acceptable;
    use risk scores to determine the risk of advanced fibrosis and
    identify those who would benefit from biopsy
    -   Fibrosis-4 (FIB 4) score
    -   NAFLD fibrosis score
    -   More accurate, non invasive fibrosis assessments can be done
        using elastography which can be vibration based (fibroscan)
        ultrasound based, or MR-based
    -   MR is nearly as accurate as biopsy (quantifying fat and
        fibrosis)
    -   Available at VUMC and can be ordered by anyone. Insurance will
        not cover if BMI \<35

Management

-   -   -   

-   Aggressive risk factor modification and mgmt of comorbidities (HLD,
    HTN, T2DM)

-   Weight loss: Mediterranean diet>Low fat diet, (dose dependent
    improvement)

-   No specific medications are FDA approved currently
    -   Pioglitazone has shown benefit in pts with T2DM and NASH
    -   Vitamin E has shown benefit in pts w/o T2DM and proven NASH
    -   Ongoing studies for SGLT-2i and GLP-1ra; some promise indicated
        for the latter

-   While bariatric surgery is not a specific indication for NASH/NAFLD,
    increasing evidence demonstrates resolution of NASH and fibrosis in
    pts with clinically significant weight loss

-   Referral to the surgical weight loss clinic should be considered in
    any patient who meets obesity guidelines for bariatric surgery
    (BMI >40, or >35 with metabolic comorbidities)

Additional Information

-   -   -   

-   Statins: should be used for HLD in pts with NASH, NAFLD and NASH
    cirrhosis

-   Statin use in decompensated NASH cirrhosis is controversial, and
    they are less likely to derive benefit given overall poor prognosis.
    There is an increased risk of rhabdomyolysis in pts with acute on
    chronic liver failure and are considered contraindicated

-   Metformin is safe and may have a **survival benefit** in patients
    with diabetes and cirrhosis. Discontinue only in those who have
    increased risk for lactic acidosis (renal impairment and significant
    EtOH). Sulfonylureas are generally avoided.

-   While hepatic steatosis and hepatic fibrosis are diagnoses that can
    be made using radiologic tools, NASH requires bx as inflammation
    plays a key role and cannot be determined radiographically or
    biochemically
