# Post-Liver Transplant Management
 
| 0                                                                      |
|------------------------------------------------------------------------|
| Post Liver Transplant Management – Lauren Evers Carlini, Gabe Sandoval |

Background

-   Immunosuppression (IS): pts typically start out on 2-3
    immunosuppression medications, including a calcineurin inhibitor
    (CNI, tacrolimus or cyclosporine), a glucocorticoid (prednisone),
    and potentially another agent (i.e., mycophenolate mofetil).
    Decreased over time, as long as there is no evidence of rejection
-   ID ppx:  PJP (trimethoprim-sulfamethoxazole), CMV if at risk for
    reactivation (valganciclovir or ganciclovir; highest risk is D+/R-;
    typically 3-6 months based on when ppx is stopped), and candida
    (fluconazole) for weeks to months after LT.
-   Screening for malignancy: post-transplant pts are at increased risk
    of malignancy due to IS. Pts must follow all standard cancer
    screening guidelines, as well as annual dermatology evaluation for
    skin cancers (high incidence of SCC).
-   Avoid live vaccines after transplantation; pts are given a list and
    in general admitted pts are not given vaccinations in house.
-   When admitted, LT recipients should have home IS meds continued
    (unless otherwise advised by attending or transplant pharmacist),
    with daily trough levels. See below.
-   Hepatology should always be consulted for these pts

Transplant medications

Tacrolimus:

-   Mainstay of post-transplant IS
-   Doses should be timed for 0600/1800 while admitted, regardless of
    home schedule
-   Pts need tacro levels QAM at 0500 while hospitalized(specific order
    in Epic);
-   Goal levels (generally):
    -   0-3 months post-transplant: 8-10 ng/mL
    -   3-12 months: 6-8 ng/mL
    -   \>12 months: 3-6 ng/mL
-   Side effects: Nephrotoxicity, neurotoxicity (HA, confusion, seizure,
    paresthesia’s, tremor; more common w/tacrolimus vs cyclosporine),
    N/V/D, hyperkalemia, hypomagnesemia, hyperglycemia, hyperuricemia,
    alopecia, HTN, HLD
-   Note: transplant pharmacists (on weekdays) are your go-to resource
    for adjusting dosage and goal levels; you will not be making these
    decisions independently

Cyclosporine:

-   Used in pts transplanted before tacrolimus was available, pts unable
    to tolerate tacrolimus, or those with a contraindication to
    tacrolimus
-   Doses should be timed for 0600/1800 while admitted, regardless of
    home schedule
-   Pts need cyclosporine levels QAM at 0500 while hospitalized
    (specific order in Epic)
-   Goal levels (generally):
    -   0-3 months post-transplant: 150-200 ng/mL
    -   3-6 months: 150 ng/mL
    -   6-12 months: 100 ng/mL
    -   \>12 months: 60-100 ng/mL
-   Side effects: Nephrotoxicity, hypomagnesemia, hyperglycemia,
    neurotoxicity (HA, tremors, paresthesia, seizure), gingival
    hyperplasia, hirsutism, malignancy (lymphoma), HTN, HLD
