# Arterial Line
 
Pre-procedure considerations

-   Palpate of artery of interest to best understand anatomy and
    surrounding structures
-   Allen Test if placing radial artery access: goal to assess
    collateral ulnar blood flow to avoid ischemia. Hold both radial and
    ulnar artery 10-15 sec to allow blanching of palm, then release
    ulnar artery to assess perfusion. If blanching quickly resolve,
    ulnar artery will allow distal perfusion
-   If attempting radial access, ensure wrist is adequately extended,
    often using towel roll under wrist and taping hand to bed or table

Procedure considerations

-   Types of Kits
    -   Arrow kit: all-in-one device that has arterial catheter over
        introducer needle
    -   A-line kit: individual introducer needle, guidewires, and
        sutures; multiple steps
    -   Micropuncture kit: atraumatic guidewire, microcatheter and
        introducer sheath
-   Reconfirm location with US after lidocaine
-   Ensure arterial access (pulsatile flow of bright red blood)

Post- procedure considerations

-   Immediately connect pressure tubing to catheter while maintaining
    sterile technique
-   If persistent bleeding, hold pressure for 15 mins.
-   Can use for frequent ABG checks
