# PFTs
 
| 0                                               |
|-------------------------------------------------|
| Pulmonary Function Tests (PFTs) – Peter Edmonds |

PFTs should rarely be ordered in inpatient setting as acute illness can
lead to suboptimal results.

Full PFTs include and can be ordered as the following:

-   Spirometry: FVC, FEV1, with or without bronchodilator
    -   Outpatient evaluation of patients with new shortness of breath,
        chronic cough, or upper airway obstruction
-   Plethysmography: TLC, RV
    -   Evaluation of restrictive diseases (ILD, neuromuscular disease)
        and/or hyperinflation (COPD, asthma)
-   Diffusion (DLCO) can be added to plethysmography.
    -   Full PFTs' = Spirometry + Plethysmography + DLCO

Tips for ordering:

-   Initial diagnostic workup
    -   Order full PFTs with bronchodilator challenge
-   Chronic Lung disease:
    -   Order spirometry only to track FEV1/FVC over time +/- DLCO to
        evaluate ILD

Interpretation:

-   Distinguish between Obstructive and Restrictive Disease
    -   FEV1/FVC \< 0.7 indicates obstructive disease
        -   Normal to increased FVC & TLC is consistent with isolated
            obstructive disease
    -   TLC \< 80% is diagnostic of restrictive disease
        -   Reduced FVC is suggestive, but not diagnostic of restrictive
            disease
        -   FEV1 commonly reduced as well, but FEV1/FVC ratio should be
            normal in isolated restrictive disease
    -   Decreased FEV1/FVC and TLC suggests a mixed obstructive and
        restrictive picture
-   Assess DLCO -- abnormal is \<75%
-   Decreased DLCO can help differentiate between causes of Obstructive
    or Restrictive PFTs

Causes of common abnormalities:

-   Obstruction
    -   DDx if DLCO decreased: COPD, CF, bronchiectasis
    -   DDx if DLCO normal: asthma, early stages of COPD or CF
    -   Asthma: spirometry may be normal, +bronchodilator response (an
        increase in FEV1 by 12% and 200ml after bronchodilator),
        +methacholine challenge
    -   Though we use FEV1/FVC to **diagnose** , we track **disease
        severity** using FEV1
-   Restriction:
    -   DDx if DLCO decreased:  ILD
    -   DDx if DLCO normal: pleural disease, chest wall (e.g. obesity,
        scoliosis), Neuromuscular disorders
-   Decreased DLCO:
    -   If PFTs otherwise normal, DDx includes pulmonary vascular
        disease, pulmonary edema, or mixed obstructive/restrictive
        disease (with pseudo-normalization of other PFTs)
