# Modes of Oxygen Delivery
 
| 0                                      |
|----------------------------------------|
| Modes of Oxygen Delivery – Blake Funke |

| 0                                | 1                       | 2                       | 3                       | 4                                                                                                                                |
|----------------------------------|-------------------------|-------------------------|-------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| Simple Delivery Systems          | Simple Delivery Systems | Simple Delivery Systems | Simple Delivery Systems | Simple Delivery Systems                                                                                                          |
| System                           | L/min                   | % O2                    | Indications             | Comments                                                                                                                         |
| Blow by                          | NaN                     | 21-100%                 | Trach collar            | NaN                                                                                                                              |
| Nasal cannula                    | 1-8                     | 25 – 45%                | Hypoxemia               | NaN                                                                                                                              |
| Large bore nasal cannula         | Up to 15                | Up to 65%               | Hypoxemia               | Can be identified by larger bore tubing (often green) and nose piece. Colloquially referred to as HFNC, but true HFNC = optiflow |
| Venturi mask                     | 4 to 15                 | 24 – 50%                | NaN                     | Actual FiO2 is dependent on pt effort                                                                                            |
| Non-rebreather                   | 10 to 15                | 65-95%                  | Severe hypoxemia        | Often used as a bridge to higher level of O2 therapy                                                                             |
| HFNC: Optiflow, AirVo, Vapotherm | Up to 60                | 30-100%                 | Severe hypoxemia        | Delivers 0.5-1 cm/H2O of PEEP per 10L of flow                                                                                    |

\*\*Use of all of the above modes of O2 requires a spontaneously
breathing pt

Non-invasive positive pressure ventilation:

-   CPAP
    -   Indications: obstructive sleep apnea, tracheomalacia
    -   Settings: CPAP, FiO2

<!-- -->

-   BiPAP
    -   Indications: hypercapnic respiratory failure (RF), hypoxic RF,
        pulmonary edema, obstructive sleep apnea, obesity
        hypoventilation syndrome, RF 2/2 neuromuscular disease
    -   Settings: IPAP, EPAP, FiO2, RR (sometimes)

| Invasive positive-pressure ventilation |                                                                   |                        |                                                                                                                                                                                                                                                                                         |
|----------------------------------------|-------------------------------------------------------------------|------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Mode                                   | You set                                                           | Not set                | Comments                                                                                                                                                                                                                                                                                |
| Pressure support (PS)                  | PEEP PS above PEEP FiO2                                           | TV RR Inspiratory flow | Similar to Bipap. Frequently used for vent weaning / SBT. Requires spontaneously breathing pt.                                                                                                                                                                                          |
| Volume Control (AC/VC)                 | PEEP RR TV Inspiratory flow FiO2                                  | Inspiratory pressure   | Mandates a minute ventilation; limits volutrauma (i.e. can guarantee LTVV) \*\*Primary mode used in MICU (mode used in major ARDS trials)                                                                                                                                               |
| SIMV                                   | PEEP RR TV PS above PEEP FiO2                                     | NaN                    | Pt gets VC breath for set rate, but if tries to breath over this will get PS breath; VC and PS breaths are synchronized when able                                                                                                                                                       |
| Pressure Control (AC/PC)               | RR Inspiratory Pressure PEEP Inspiratory Time (or I:E ratio) FiO2 | TV                     | Minimizes barotrauma (i.e. sets a max inspiratory pressure)  does not guarantee a specific minute ventilation (must monitor PCO2 with blood gases) Does not have natural ventilator alarms for protection – need to increase low minute ventilation alarm threshold                    |
| PRVC                                   | PEEP RR TV Inspiratory flow Pressure max FiO2                     | NaN                    | Adaptive pressure control (NOT actually a volume control mode); tries to limit both barotrauma and volutrauma but if in conflict, minute ventilation will drop (i.e. need to monitor PCO2 with blood gases like any other PC mode) Con: More the pt works, the less the ventilator does |
| APRV / Bilevel                         | PEEP (PLow) Pressure High Time Low Time High FiO2                 | TV                     | Long periods of inspiratory holds and very brief expirations (i.e. releases) Often difficult to ventilate pts on this mode                                                                                                                                                              |
