on:
  push:
     branches:
       - main

name: build bookdown

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install pdflatex
        run: |
          Rscript -e 'install.packages(c("tinytex"))'
          Rscript -e 'tinytex::install_tinytex()'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: change file extensions

          cd docs
          for f in **/*.md; do mv "$f" "${f%%.md}".Rmd; done
      - name: Render Book
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
#          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'
#          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::epub_book")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
  
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          email: ${{ secrets.EMAIL }}
          build_dir: _book  # optional
          branch: gh-pages  # optional
          jekyll: no        # optional
